# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EventRaidStart.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EventRaidStart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x45ventRaidStart.proto\x12\x04\x45sPb\"5\n\x0e\x45ventRaidStart\x12#\n\teventRaid\x18\x01 \x01(\x0b\x32\x10.EsPb.sEventRaid\"\x80\x02\n\nsEventRaid\x12\x12\n\neventGroup\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ventNumber\x18\x02 \x01(\x05\x12\x10\n\x08\x65nterCnt\x18\x03 \x01(\x05\x12\x11\n\tstageStep\x18\x04 \x01(\x05\x12\x11\n\tmaxDemage\x18\x05 \x01(\x03\x12\x1b\n\x13maxDemageLastReward\x18\x06 \x01(\x03\x12\x13\n\x0b\x61\x63\x63umDemage\x18\x07 \x01(\x03\x12\x1d\n\x15\x61\x63\x63umDemageLastReward\x18\x08 \x01(\x03\x12+\n\reventRaidHero\x18\t \x03(\x0b\x32\x14.EsPb.sEventRaidHero\x12\x13\n\x0b\x64iaUseCount\x18\n \x01(\x05\">\n\x0esEventRaidHero\x12\x0e\n\x06heroNo\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EventRaidStart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTRAIDSTART']._serialized_start=30
  _globals['_EVENTRAIDSTART']._serialized_end=83
  _globals['_SEVENTRAID']._serialized_start=86
  _globals['_SEVENTRAID']._serialized_end=342
  _globals['_SEVENTRAIDHERO']._serialized_start=344
  _globals['_SEVENTRAIDHERO']._serialized_end=406
# @@protoc_insertion_point(module_scope)
