# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EventPassList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EventPassList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x45ventPassList.proto\x12\x04\x45sPb\"4\n\rEventPassList\x12#\n\teventPass\x18\x01 \x03(\x0b\x32\x10.EsPb.sEventPass\"\x91\x01\n\nsEventPass\x12\r\n\x05point\x18\x01 \x01(\x05\x12\x15\n\rrewardedPoint\x18\x02 \x01(\x05\x12\x13\n\x0bisBuyTicket\x18\x03 \x01(\x05\x12\x11\n\texpiredDt\x18\x04 \x01(\x03\x12\x11\n\teventType\x18\x05 \x01(\x05\x12\r\n\x05group\x18\x06 \x01(\x05\x12\x13\n\x0b\x65ventNumber\x18\x07 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EventPassList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTPASSLIST']._serialized_start=29
  _globals['_EVENTPASSLIST']._serialized_end=81
  _globals['_SEVENTPASS']._serialized_start=84
  _globals['_SEVENTPASS']._serialized_end=229
# @@protoc_insertion_point(module_scope)
