# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EverLiveInfo.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'EverLiveInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x45verLiveInfo.proto\x12\x04\x45sPb\"Y\n\x0c\x45verLiveInfo\x12!\n\x08\x65verLive\x18\x01 \x03(\x0b\x32\x0f.EsPb.sEverLive\x12&\n\x07rewards\x18\x02 \x03(\x0b\x32\x15.EsPb.sEverLiveReward\"\xac\x01\n\tsEverLive\x12\x0f\n\x07groupNo\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ventNumber\x18\x02 \x01(\x05\x12\x0f\n\x07stageNo\x18\x03 \x01(\x05\x12\x11\n\tstageMode\x18\x04 \x01(\x05\x12\x12\n\nclearCount\x18\x05 \x01(\x05\x12\x13\n\x0b\x63learYymmdd\x18\x06 \x01(\x05\x12\x14\n\x0cperfectCount\x18\x07 \x01(\x05\x12\x16\n\x0esignatureCount\x18\x08 \x01(\x05\"\xc1\x01\n\x0fsEverLiveReward\x12\x12\n\neventGroup\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ventNumber\x18\x02 \x01(\x05\x12\x11\n\tstageMode\x18\x03 \x01(\x05\x12\x12\n\nrepeatType\x18\x04 \x01(\x05\x12\x12\n\nclearStage\x18\x05 \x01(\x05\x12\x12\n\nrewardType\x18\x06 \x01(\x05\x12\x12\n\ngoalAmount\x18\x07 \x01(\x05\x12\x10\n\x08isReward\x18\x08 \x01(\x05\x12\x10\n\x08rewardNo\x18\t \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EverLiveInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVERLIVEINFO']._serialized_start=28
  _globals['_EVERLIVEINFO']._serialized_end=117
  _globals['_SEVERLIVE']._serialized_start=120
  _globals['_SEVERLIVE']._serialized_end=292
  _globals['_SEVERLIVEREWARD']._serialized_start=295
  _globals['_SEVERLIVEREWARD']._serialized_end=488
# @@protoc_insertion_point(module_scope)
