# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GachaMileageInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GachaMileageInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GachaMileageInfo.proto\x12\x04\x45sPb\"=\n\x10GachaMileageInfo\x12)\n\x0cgachaMileage\x18\x01 \x03(\x0b\x32\x13.EsPb.sGachaMileage\"c\n\rsGachaMileage\x12\x11\n\tmileageNo\x18\x01 \x01(\x05\x12\x14\n\x0c\x63hangedPoint\x18\x02 \x01(\x05\x12\x12\n\nafterPoint\x18\x03 \x01(\x05\x12\x15\n\rrewardedPoint\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaMileageInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GACHAMILEAGEINFO']._serialized_start=32
  _globals['_GACHAMILEAGEINFO']._serialized_end=93
  _globals['_SGACHAMILEAGE']._serialized_start=95
  _globals['_SGACHAMILEAGE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
