# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GuildRaidInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GuildRaidInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GuildRaidInfo.proto\x12\x04\x45sPb\"\xa9\x02\n\rGuildRaidInfo\x12\x0c\n\x04open\x18\x01 \x01(\x05\x12\x10\n\x08remainTs\x18\x02 \x01(\x03\x12\x12\n\nscheduleId\x18\x03 \x01(\x05\x12\x12\n\ntodayScore\x18\x04 \x01(\x03\x12\x10\n\x08maxScore\x18\x05 \x01(\x03\x12\x12\n\ntotalScore\x18\x06 \x01(\x03\x12\x11\n\tguildRank\x18\x07 \x01(\x05\x12\x17\n\x0fguildTotalScore\x18\x08 \x01(\x03\x12#\n\x1bguildRaidOpenNotificationDt\x18\t \x01(\x03\x12\x11\n\tremainCnt\x18\n \x01(\x05\x12\x0e\n\x06maxCnt\x18\x0b \x01(\x05\x12\x36\n\x11seasonRewardState\x18\x0c \x01(\x0e\x32\x1b.EsPb.eGuildRaidRewardState*j\n\x15\x65GuildRaidRewardState\x12\x13\n\x0f\x41lreadyRewarded\x10\x00\x12\r\n\tCanReward\x10\x01\x12\r\n\tNoHistory\x10\x02\x12\x0f\n\x0b\x43\x61lculating\x10\x03\x12\r\n\tInProcess\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GuildRaidInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EGUILDRAIDREWARDSTATE']._serialized_start=329
  _globals['_EGUILDRAIDREWARDSTATE']._serialized_end=435
  _globals['_GUILDRAIDINFO']._serialized_start=30
  _globals['_GUILDRAIDINFO']._serialized_end=327
# @@protoc_insertion_point(module_scope)
