# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HeroCostumeEquip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HeroCostumeEquip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16HeroCostumeEquip.proto\x12\x04\x45sPb\"@\n\x10HeroCostumeEquip\x12,\n\rheroRepuation\x18\x01 \x01(\x0b\x32\x15.EsPb.sHeroReputation\"\x9c\x02\n\x0fsHeroReputation\x12\x0e\n\x06heroNo\x18\x01 \x01(\x05\x12\x12\n\nreputation\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x05\x12\x0e\n\x06stress\x18\x04 \x01(\x05\x12\x14\n\x0clastUpdateDt\x18\x05 \x01(\x03\x12\x0e\n\x06giftDt\x18\x06 \x01(\x03\x12\x15\n\rcostumeItemNo\x18\x07 \x01(\x05\x12\x13\n\x0bstoryReward\x18\x08 \x01(\x05\x12\x13\n\x0bmaxGradeSno\x18\t \x01(\x05\x12\x10\n\x08objetUid\x18\n \x01(\x05\x12\x12\n\nmaxLevelDt\x18\x0b \x01(\x03\x12\x11\n\tarbeitExp\x18\x0c \x01(\x05\x12\x10\n\x08priority\x18\r \x01(\x05\x12\x14\n\x0crestFinishDt\x18\x0e \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroCostumeEquip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEROCOSTUMEEQUIP']._serialized_start=32
  _globals['_HEROCOSTUMEEQUIP']._serialized_end=96
  _globals['_SHEROREPUTATION']._serialized_start=99
  _globals['_SHEROREPUTATION']._serialized_end=383
# @@protoc_insertion_point(module_scope)
