# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShopRandomList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ShopRandomList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ShopRandomList.proto\x12\x04\x45sPb\"\x83\x01\n\x0eShopRandomList\x12\x0e\n\x06shopNo\x18\x01 \x01(\x05\x12\x17\n\x0fshopDrawBoxStep\x18\x02 \x01(\x05\x12\x1d\n\x15shopDrawBoxRepeatStep\x18\x03 \x01(\x05\x12)\n\nboughtItem\x18\x04 \x03(\x0b\x32\x15.EsPb.sShopRandomItem\"4\n\x0fsShopRandomItem\x12\x0e\n\x06itemNo\x18\x01 \x01(\x05\x12\x11\n\tdrewCount\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ShopRandomList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOPRANDOMLIST']._serialized_start=31
  _globals['_SHOPRANDOMLIST']._serialized_end=162
  _globals['_SSHOPRANDOMITEM']._serialized_start=164
  _globals['_SSHOPRANDOMITEM']._serialized_end=216
# @@protoc_insertion_point(module_scope)
