# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureUpgrade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SignatureUpgrade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SignatureUpgrade.proto\x12\x04\x45sPb\"`\n\x10SignatureUpgrade\x12+\n\ritemSignature\x18\x01 \x01(\x0b\x32\x14.EsPb.sItemSignature\x12\x1f\n\x07itemEtc\x18\x02 \x01(\x0b\x32\x0e.EsPb.sItemEtc\">\n\x0esItemSignature\x12\x0e\n\x06itemNo\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\"\'\n\x08sItemEtc\x12\x0e\n\x06itemNo\x18\x01 \x01(\x05\x12\x0b\n\x03\x63nt\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignatureUpgrade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNATUREUPGRADE']._serialized_start=32
  _globals['_SIGNATUREUPGRADE']._serialized_end=128
  _globals['_SITEMSIGNATURE']._serialized_start=130
  _globals['_SITEMSIGNATURE']._serialized_end=192
  _globals['_SITEMETC']._serialized_start=194
  _globals['_SITEMETC']._serialized_end=233
# @@protoc_insertion_point(module_scope)
