# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TaskList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TaskList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eTaskList.proto\x12\x04\x45sPb\"V\n\x08TaskList\x12#\n\ttaskDaily\x18\x01 \x01(\x0b\x32\x10.EsPb.sTaskDaily\x12%\n\ntaskWeekly\x18\x02 \x01(\x0b\x32\x11.EsPb.sTaskWeekly\"h\n\nsTaskDaily\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\r\x12#\n\ttaskValue\x18\x02 \x03(\x0b\x32\x10.EsPb.sTaskValue\x12\'\n\x0btaskReceive\x18\x03 \x03(\x0b\x32\x12.EsPb.sTaskReceive\"\x19\n\nsTaskValue\x12\x0b\n\x03val\x18\x01 \x01(\r\"\x1b\n\x0csTaskReceive\x12\x0b\n\x03val\x18\x01 \x01(\r\"j\n\x0bsTaskWeekly\x12\r\n\x05weeks\x18\x01 \x01(\r\x12#\n\ttaskValue\x18\x02 \x03(\x0b\x32\x10.EsPb.sTaskValue\x12\'\n\x0btaskReceive\x18\x03 \x03(\x0b\x32\x12.EsPb.sTaskReceiveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TaskList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKLIST']._serialized_start=24
  _globals['_TASKLIST']._serialized_end=110
  _globals['_STASKDAILY']._serialized_start=112
  _globals['_STASKDAILY']._serialized_end=216
  _globals['_STASKVALUE']._serialized_start=218
  _globals['_STASKVALUE']._serialized_end=243
  _globals['_STASKRECEIVE']._serialized_start=245
  _globals['_STASKRECEIVE']._serialized_end=272
  _globals['_STASKWEEKLY']._serialized_start=274
  _globals['_STASKWEEKLY']._serialized_end=380
# @@protoc_insertion_point(module_scope)
