package com.kakaogame.secondpw;

import com.liapp.y;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;

/* compiled from: ActionType.kt */
@Metadata(m838d1 = {"\u0000\f\n\u0000\n\u0002\u0018\u0002\n\u0002\u0010\u000e\n\u0000\u001a\n\u0010\u0000\u001a\u00020\u0001*\u00020\u0002¨\u0006\u0003"}, m839d2 = {"getActionType", "Lcom/kakaogame/secondpw/ActionType;", "", "security_release"}, m840k = 2, m841mv = {1, 9, 0}, m843xi = 48)
/* loaded from: classes3.dex */
public final class ActionTypeKt {
    /* JADX WARN: Unreachable blocks removed: 1, instructions: 1 */
    public static final ActionType getActionType(String str) {
        Intrinsics.checkNotNullParameter(str, y.٬ݯح׭٩(575694806));
        return Intrinsics.areEqual(str, ActionType.ENTER_IS_ALLOWED_ACCESS.getValue()) ? ActionType.ENTER_IS_ALLOWED_ACCESS : Intrinsics.areEqual(str, ActionType.ENTER_SHOW_PASSWORD_SETTING_VIEW.getValue()) ? ActionType.ENTER_SHOW_PASSWORD_SETTING_VIEW : Intrinsics.areEqual(str, ActionType.SHOW_RESTRICT_POPUP.getValue()) ? ActionType.SHOW_RESTRICT_POPUP : Intrinsics.areEqual(str, ActionType.SHOW_PUT_PASSWORD.getValue()) ? ActionType.SHOW_PUT_PASSWORD : Intrinsics.areEqual(str, ActionType.SET_REQUEST_CODE.getValue()) ? ActionType.SET_REQUEST_CODE : Intrinsics.areEqual(str, ActionType.SET_CODE_TALK.getValue()) ? ActionType.SET_CODE_TALK : Intrinsics.areEqual(str, ActionType.SET_CODE_SMS.getValue()) ? ActionType.SET_CODE_SMS : Intrinsics.areEqual(str, ActionType.SET_CODE_EMAIL.getValue()) ? ActionType.SET_CODE_EMAIL : Intrinsics.areEqual(str, ActionType.SET_AGREE.getValue()) ? ActionType.SET_AGREE : Intrinsics.areEqual(str, ActionType.SET_PHONE_NUMBER.getValue()) ? ActionType.SET_PHONE_NUMBER : Intrinsics.areEqual(str, ActionType.SET_EMAIL.getValue()) ? ActionType.SET_EMAIL : Intrinsics.areEqual(str, ActionType.RESET_DIGIT_CODE_1.getValue()) ? ActionType.RESET_DIGIT_CODE_1 : Intrinsics.areEqual(str, ActionType.RESET_DIGIT_CODE_2.getValue()) ? ActionType.RESET_DIGIT_CODE_2 : Intrinsics.areEqual(str, ActionType.KEYPAD_TIME_LIMIT.getValue()) ? ActionType.KEYPAD_TIME_LIMIT : Intrinsics.areEqual(str, ActionType.KEYPAD_TIME_LIMIT_1.getValue()) ? ActionType.KEYPAD_TIME_LIMIT_1 : Intrinsics.areEqual(str, ActionType.KEYPAD_TIME_LIMIT_2.getValue()) ? ActionType.KEYPAD_TIME_LIMIT_2 : Intrinsics.areEqual(str, ActionType.SET_PASSWORD.getValue()) ? ActionType.SET_PASSWORD : Intrinsics.areEqual(str, ActionType.SET_COMPLETE.getValue()) ? ActionType.SET_COMPLETE : Intrinsics.areEqual(str, ActionType.REQUEST_RESET.getValue()) ? ActionType.REQUEST_RESET : Intrinsics.areEqual(str, ActionType.REQUEST_REMOVE.getValue()) ? ActionType.REQUEST_REMOVE : Intrinsics.areEqual(str, ActionType.PUT_PASSWORD.getValue()) ? ActionType.PUT_PASSWORD : Intrinsics.areEqual(str, ActionType.RESET_REQUEST_CODE.getValue()) ? ActionType.RESET_REQUEST_CODE : Intrinsics.areEqual(str, ActionType.RESET_CODE.getValue()) ? ActionType.RESET_CODE : Intrinsics.areEqual(str, ActionType.RESET_PASSWORD.getValue()) ? ActionType.RESET_PASSWORD : Intrinsics.areEqual(str, ActionType.RESET_COMPLETE.getValue()) ? ActionType.RESET_COMPLETE : Intrinsics.areEqual(str, ActionType.REMOVE_CONFIRM.getValue()) ? ActionType.REMOVE_CONFIRM : Intrinsics.areEqual(str, ActionType.REMOVE_REQUEST_CODE.getValue()) ? ActionType.REMOVE_REQUEST_CODE : Intrinsics.areEqual(str, ActionType.REMOVE_CODE.getValue()) ? ActionType.REMOVE_CODE : Intrinsics.areEqual(str, ActionType.REMOVE_COMPLETE.getValue()) ? ActionType.REMOVE_COMPLETE : Intrinsics.areEqual(str, ActionType.CLOSE_POPUP.getValue()) ? ActionType.CLOSE_POPUP : Intrinsics.areEqual(str, ActionType.RESTRICT_ACCESS.getValue()) ? ActionType.RESTRICT_ACCESS : ActionType.EXIT;
    }
}
