syntax = "proto3";

package EsPb;

message sBattleSaveDeck {
  repeated sBattleSaveHero hero = 1;
  repeated sFormation formation = 2;
  repeated sContentBuff buff = 3;
  repeated sContentBuff rentalBuff = 4;
}

message sBattleSaveHero {
  sHero hero = 1;
  repeated sItemEquipAndEquipSlot itemEquip = 2;
  repeated int32 equipSetBuff = 3;
  sItemSignature signature = 4;
  bool isRental = 5;
}

message sHero {
  string idx = 1;
  int32 heroNo = 2;
  int32 level = 3;
  int32 isResonance = 4;
  int32 gradeSno = 5;
  int32 raceSno = 6;
  int32 isLock = 7;
}

message sItemEquipAndEquipSlot {
  int64 id = 1;
  int32 itemNo = 2;
  int32 exp = 3;
  int32 slot = 4;
}

message sItemSignature {
  int32 itemNo = 1;
  int32 grade = 2;
  int32 level = 3;
}

message sFormation {
  int32 no = 1;
  int32 kind = 2;
  repeated string heroidx = 3;
  int32 formationType = 4;
  string formationName = 5;
  sRelic relic = 6;
}

message sRelic {
  int32 type = 1;
  int32 formation = 2;
  int32 relicOrder = 3;
  int32 relicNo = 4;
}

message sContentBuff {
  int32 contentType = 1;
  int32 buffType = 2;
  int32 buffNo = 3;
  int32 value = 4;
}

