syntax = "proto3";

package EsPb;

enum eDoubleGateStageType {
  DoubleGateStageTypeNone = 0;
  DoubleGateNormalManaCrystal = 1;
  DoubleGateNormalGold = 2;
  DoubleGateNormalManaDust = 3;
  DoubleGateNormalEnhanceStone = 4;
}

message sDoubleGateInfo {
  int32 firstDoubleGateRotateId = 1;
  int32 firstDoubleGateGroupNo = 2;
  int32 secondDoubleGateRotateId = 3;
  int32 secondDoubleGateGroupNo = 4;
  int32 buffNo = 5;
  int32 debuffNo = 6;
  int32 globalDebuffNo = 7;
  eDoubleGateStageType stageType = 8;
}

