namespace Dungeon;

table Deserialization {
    no: int32;
    name_sno: int32;
    desc_sno: int32;
    list_sno: int32;
    dungeon_type: int32;
    rotation_priority: int32;
    hero_count_max: int32;
    hero_level_min: int32;
    hero_grade_min: int32;
    race_buff_noOffset: string;
    dungeon_buff_noOffset: string;
    monster_tribe: int32;
    advantage_tribe: int32;
    disadvantage_tribe: int32;
    dungeon_list_imageOffset: string;
    dungeon_info_imageOffset: string;
    dungeon_mapOffset: string;
    dungeon_leveldesignOffset: string;
    mission_group_no: int32;
    minimap_title_sno: int32;
    hide_uiOffset: string;
    is_usable: int32;
    sound_bgmOffset: string;
    sound_ambienceOffset: string;
}

table Dungeon {
    json: [Deserialization];
}

root_type Dungeon;
