namespace EdenUnionRank;

table Deserialization {
    no: int32;
    union_group: int32;
    tier_no: int32;
    rank_from: int32;
    rank_to: int32;
    tier_string_no: int32;
    tier_path: string;
    reward_item_no1: int32;
    reward_item_amount1: int32;
    reward_item_no2: int32;
    reward_item_amount2: int32;
    reward_item_no3: int32;
    reward_item_amount3: int32;
    reward_item_no4: int32;
    reward_item_amount4: int32;
}

table EdenUnionRank {
    json: [Deserialization];
}

root_type EdenUnionRank;
