namespace EventRotation;

table Deserialization {
    no: int32;
    group: int32;
    event_number: int32;
    reward_path: int32;
    table_nameOffset: string;
    column_name_1Offset: string;
    value_1: float;
    column_name_2Offset: string;
    value_2: float;
    column_name_3Offset: string;
    value_3: float;
    column_name_4Offset: string;
    value_4: float;
    column_name_5Offset: string;
    value_5: float;
    column_name_6Offset: string;
    value_6: float;
    column_name_7Offset: string;
    value_7: float;
    column_name_8Offset: string;
    value_8: float;
    column_name_9Offset: string;
    value_9: float;
    column_name_10Offset: string;
    value_10: float;
}

table EventRotation {
    json: [Deserialization];
}

root_type EventRotation;
