namespace EventDefenseWaveSetting;

table Deserialization {
    no: int32;
    event_group: int32;
    wave_start_time: int32;
    wave_monster_no1: int32;
    wave_monster_amount1: int32;
    wave_monster_no2: int32;
    wave_monster_amount2: int32;
    wave_monster_no3: int32;
    wave_monster_amount3: int32;
    wave_monster_no4: int32;
    wave_monster_amount4: int32;
    wave_monster_no5: int32;
    wave_monster_amount5: int32;
}

table EventDefenseWaveSetting {
    json: [Deserialization];
}

root_type EventDefenseWaveSetting;
