namespace ShopRandom;

table Deserialization {
    no: int32;
    shop_no: int32;
    pay_item_no: int32;
    pay_item_amount: int32;
    repeat_draw_box: string;
    bg_path: string;
    shop_image_path: string;
    use_title: int32;
    shop_name_sno: int32;
    event_shop_hero: int32;
    model_viewer_display: int32;
    model_offset: string;
    tip_sno1: int32;
    tip_sno2: int32;
    tip_sno3: int32;
    tip2_sno1: int32;
    tip2_sno2: int32;
    tip2_sno3: int32;
    tip3_sno1: int32;
    tip3_sno2: int32;
    tip3_sno3: int32;
}

table ShopRandom {
    json: [Deserialization];
}

root_type ShopRandom;
