namespace SingleRaid;

table Deserialization {
    no: int32;
    level_group: int32;
    stage_no: int32;
    guide_sno: int32;
    story_no: int32;
    is_special: int32;
    bg_pathOffset: string;
    event_bg_pathOffset: string;
    bg_positionOffset: string;
    sound_pathOffset: string;
    behavior_1: int32;
    behavior_2: int32;
    behavior_3: int32;
    behavior_4: int32;
    behavior_5: int32;
    behavior_6: int32;
    behavior_7: int32;
    behavior_8: int32;
    quest_category: int32;
}

table SingleRaid {
    json: [Deserialization];
}

root_type SingleRaid;
