namespace Talk;

table Deserialization {
    no: int32;
    hide: int8;
    group_no: int32;
    love_level: int8;
    hero_no: int16;
    talk_type: int16;
    ui_typeOffset: string;
    transition_typeOffset: string;
    transition_bg_typeOffset: string;
    speaking: int16;
    speaker_no: int16;
    talk_index: int16;
    choice_group: int16;
    affinity_point: int16;
    position_center: int16;
    motionway_center: int16;
    ani_centerOffset: string;
    emotion_centerOffset: string;
    position_left: int16;
    motionway_left: int16;
    ani_leftOffset: string;
    emotion_leftOffset: string;
    position_right: int16;
    motionway_right: int16;
    ani_rightOffset: string;
    emotion_rightOffset: string;
    position_type: int16;
    position_bg_typeOffset: string;
    opacity: int8;
    small_port: int16;
    fx_effectOffset: string;
    fg_imageOffset: string;
    bg_imageOffset: string;
    light_typeOffset: string;
    bg_movieOffset: string;
    videoOffset: string;
    cutscene: int32;
    bg_soundOffset: string;
    fx_soundOffset: string;
    voiceOffset: string;
    amb_soundOffset: string;
}

table Talk {
    json: [Deserialization];
}

root_type Talk;
