namespace TalkBubble;

table Deserialization {
    hero_no: int32;
    bubble_talk1: int64;
    bubble_talk2: int64;
    bubble_talk3: int64;
    arbeit_start: int64;
    arbeit_finish: int64;
    sad_talk1: int64;
    sad_talk2: int64;
    sad_talk3: int64;
    sad_ani1Offset: string;
    sad_ani2Offset: string;
    sad_ani3Offset: string;
    happy_talk1: int64;
    happy_talk2: int64;
    happy_talk3: int64;
    happy_ani1Offset: string;
    happy_ani2Offset: string;
    happy_ani3Offset: string;
    lovely_talk: int64;
    lovely_aniOffset: string;
    hit_reaction1: int32;
    hit_reaction2: int32;
    hit_reaction3: int32;
    hit_reaction_strong1: int32;
    hit_reaction_strong2: int32;
    hit_reaction_strong3: int32;
}

table TalkBubble {
    json: [Deserialization];
}

root_type TalkBubble;
