# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CashDailyNList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CashDailyNList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43\x61shDailyNList.proto\x12\x04\x45sPb\"7\n\x0e\x43\x61shDailyNList\x12%\n\ncashDailyN\x18\x01 \x03(\x0b\x32\x11.EsPb.sCashDailyN\"M\n\x0bsCashDailyN\x12\x11\n\tpackageNo\x18\x01 \x01(\x05\x12\x16\n\x0erewardYyyymmdd\x18\x02 \x01(\x05\x12\x13\n\x0b\x65ndYyyymmdd\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CashDailyNList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CASHDAILYNLIST']._serialized_start=30
  _globals['_CASHDAILYNLIST']._serialized_end=85
  _globals['_SCASHDAILYN']._serialized_start=87
  _globals['_SCASHDAILYN']._serialized_end=164
# @@protoc_insertion_point(module_scope)
