# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HeroLockUpdate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HeroLockUpdate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14HeroLockUpdate.proto\x12\x04\x45sPb\"+\n\x0eHeroLockUpdate\x12\x19\n\x04hero\x18\x01 \x01(\x0b\x32\x0b.EsPb.sHero\"{\n\x05sHero\x12\x0b\n\x03idx\x18\x01 \x01(\t\x12\x0e\n\x06heroNo\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x13\n\x0bisResonance\x18\x04 \x01(\x05\x12\x10\n\x08gradeSno\x18\x05 \x01(\x05\x12\x0f\n\x07raceSno\x18\x06 \x01(\x05\x12\x0e\n\x06isLock\x18\x07 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroLockUpdate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEROLOCKUPDATE']._serialized_start=30
  _globals['_HEROLOCKUPDATE']._serialized_end=73
  _globals['_SHERO']._serialized_start=75
  _globals['_SHERO']._serialized_end=198
# @@protoc_insertion_point(module_scope)
