# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VistaHeroSave.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'VistaHeroSave.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13VistaHeroSave.proto\x12\x04\x45sPb\"Y\n\rVistaHeroSave\x12#\n\tvistaInfo\x18\x01 \x01(\x0b\x32\x10.EsPb.sVistaInfo\x12#\n\tvistaHero\x18\x02 \x01(\x0b\x32\x10.EsPb.sVistaHero\"\x93\x01\n\nsVistaInfo\x12\x0f\n\x07vistaNo\x18\x01 \x01(\x05\x12\x15\n\rmaxClearLevel\x18\x02 \x01(\x05\x12\x16\n\x0emaxRewardLevel\x18\x03 \x01(\x05\x12\x1b\n\x13vistaTreasureEnergy\x18\x04 \x01(\x05\x12\x10\n\x08\x65xpireDt\x18\x05 \x01(\x03\x12\x16\n\x0e\x65nergyUpdateDt\x18\x06 \x01(\x03\"\x1c\n\nsVistaHero\x12\x0e\n\x06heroNo\x18\x01 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VistaHeroSave_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VISTAHEROSAVE']._serialized_start=29
  _globals['_VISTAHEROSAVE']._serialized_end=118
  _globals['_SVISTAINFO']._serialized_start=121
  _globals['_SVISTAINFO']._serialized_end=268
  _globals['_SVISTAHERO']._serialized_start=270
  _globals['_SVISTAHERO']._serialized_end=298
# @@protoc_insertion_point(module_scope)
