# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AlchemistGachaProbs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AlchemistGachaProbs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAlchemistGachaProbs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AlchemistGachaProbs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AlchemistGachaProbs
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AlchemistGachaProbs
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AlchemistGachaProbs
    def ItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AlchemistGachaProbs
    def ItemAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AlchemistGachaProbs
    def Prob(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def AlchemistGachaProbsStart(builder):
    builder.StartObject(5)

def Start(builder):
    AlchemistGachaProbsStart(builder)

def AlchemistGachaProbsAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    AlchemistGachaProbsAddNo(builder, no)

def AlchemistGachaProbsAddType(builder, type):
    builder.PrependInt32Slot(1, type, 0)

def AddType(builder, type):
    AlchemistGachaProbsAddType(builder, type)

def AlchemistGachaProbsAddItemNo(builder, itemNo):
    builder.PrependInt32Slot(2, itemNo, 0)

def AddItemNo(builder, itemNo):
    AlchemistGachaProbsAddItemNo(builder, itemNo)

def AlchemistGachaProbsAddItemAmount(builder, itemAmount):
    builder.PrependInt32Slot(3, itemAmount, 0)

def AddItemAmount(builder, itemAmount):
    AlchemistGachaProbsAddItemAmount(builder, itemAmount)

def AlchemistGachaProbsAddProb(builder, prob):
    builder.PrependInt32Slot(4, prob, 0)

def AddProb(builder, prob):
    AlchemistGachaProbsAddProb(builder, prob)

def AlchemistGachaProbsEnd(builder):
    return builder.EndObject()

def End(builder):
    return AlchemistGachaProbsEnd(builder)
