# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArenaRelic(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArenaRelic()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArenaRelic(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArenaRelic
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArenaRelic
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def Foe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def GradeSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def BattlebuffNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def RelicType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def IconImg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArenaRelic
    def NameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaRelic
    def DescSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ArenaRelicStart(builder):
    builder.StartObject(9)

def Start(builder):
    ArenaRelicStart(builder)

def ArenaRelicAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    ArenaRelicAddNo(builder, no)

def ArenaRelicAddFoe(builder, foe):
    builder.PrependInt32Slot(1, foe, 0)

def AddFoe(builder, foe):
    ArenaRelicAddFoe(builder, foe)

def ArenaRelicAddGroup(builder, group):
    builder.PrependInt32Slot(2, group, 0)

def AddGroup(builder, group):
    ArenaRelicAddGroup(builder, group)

def ArenaRelicAddGradeSno(builder, gradeSno):
    builder.PrependInt32Slot(3, gradeSno, 0)

def AddGradeSno(builder, gradeSno):
    ArenaRelicAddGradeSno(builder, gradeSno)

def ArenaRelicAddBattlebuffNo(builder, battlebuffNo):
    builder.PrependInt32Slot(4, battlebuffNo, 0)

def AddBattlebuffNo(builder, battlebuffNo):
    ArenaRelicAddBattlebuffNo(builder, battlebuffNo)

def ArenaRelicAddRelicType(builder, relicType):
    builder.PrependInt32Slot(5, relicType, 0)

def AddRelicType(builder, relicType):
    ArenaRelicAddRelicType(builder, relicType)

def ArenaRelicAddIconImg(builder, iconImg):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(iconImg), 0)

def AddIconImg(builder, iconImg):
    ArenaRelicAddIconImg(builder, iconImg)

def ArenaRelicAddNameSno(builder, nameSno):
    builder.PrependInt32Slot(7, nameSno, 0)

def AddNameSno(builder, nameSno):
    ArenaRelicAddNameSno(builder, nameSno)

def ArenaRelicAddDescSno(builder, descSno):
    builder.PrependInt32Slot(8, descSno, 0)

def AddDescSno(builder, descSno):
    ArenaRelicAddDescSno(builder, descSno)

def ArenaRelicEnd(builder):
    return builder.EndObject()

def End(builder):
    return ArenaRelicEnd(builder)
