# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArkOverClock(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArkOverClock()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArkOverClock(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArkOverClock
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArkOverClock
    def OverclockLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArkOverClock
    def ManaCrystal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArkOverClock
    def PayItemNo0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArkOverClock
    def PayAmount0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArkOverClock
    def PayItemNo1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArkOverClock
    def PayAmount1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ArkOverClockStart(builder):
    builder.StartObject(6)

def Start(builder):
    ArkOverClockStart(builder)

def ArkOverClockAddOverclockLevel(builder, overclockLevel):
    builder.PrependInt32Slot(0, overclockLevel, 0)

def AddOverclockLevel(builder, overclockLevel):
    ArkOverClockAddOverclockLevel(builder, overclockLevel)

def ArkOverClockAddManaCrystal(builder, manaCrystal):
    builder.PrependInt32Slot(1, manaCrystal, 0)

def AddManaCrystal(builder, manaCrystal):
    ArkOverClockAddManaCrystal(builder, manaCrystal)

def ArkOverClockAddPayItemNo0(builder, payItemNo0):
    builder.PrependInt32Slot(2, payItemNo0, 0)

def AddPayItemNo0(builder, payItemNo0):
    ArkOverClockAddPayItemNo0(builder, payItemNo0)

def ArkOverClockAddPayAmount0(builder, payAmount0):
    builder.PrependInt32Slot(3, payAmount0, 0)

def AddPayAmount0(builder, payAmount0):
    ArkOverClockAddPayAmount0(builder, payAmount0)

def ArkOverClockAddPayItemNo1(builder, payItemNo1):
    builder.PrependInt32Slot(4, payItemNo1, 0)

def AddPayItemNo1(builder, payItemNo1):
    ArkOverClockAddPayItemNo1(builder, payItemNo1)

def ArkOverClockAddPayAmount1(builder, payAmount1):
    builder.PrependInt32Slot(5, payAmount1, 0)

def AddPayAmount1(builder, payAmount1):
    ArkOverClockAddPayAmount1(builder, payAmount1)

def ArkOverClockEnd(builder):
    return builder.EndObject()

def End(builder):
    return ArkOverClockEnd(builder)
