# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttendanceTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttendanceTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttendanceTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttendanceTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttendanceTable
    def Attendances(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Attendance import Attendance
            obj = Attendance()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AttendanceTable
    def AttendancesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AttendanceTable
    def AttendancesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def AttendanceTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    AttendanceTableStart(builder)

def AttendanceTableAddAttendances(builder, attendances):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(attendances), 0)

def AddAttendances(builder, attendances):
    AttendanceTableAddAttendances(builder, attendances)

def AttendanceTableStartAttendancesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttendancesVector(builder, numElems):
    return AttendanceTableStartAttendancesVector(builder, numElems)

def AttendanceTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttendanceTableEnd(builder)
