# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BackgroundTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackgroundTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBackgroundTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BackgroundTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackgroundTable
    def Backgrounds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Background import Background
            obj = Background()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BackgroundTable
    def BackgroundsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BackgroundTable
    def BackgroundsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BackgroundTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    BackgroundTableStart(builder)

def BackgroundTableAddBackgrounds(builder, backgrounds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(backgrounds), 0)

def AddBackgrounds(builder, backgrounds):
    BackgroundTableAddBackgrounds(builder, backgrounds)

def BackgroundTableStartBackgroundsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBackgroundsVector(builder, numElems):
    return BackgroundTableStartBackgroundsVector(builder, numElems)

def BackgroundTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return BackgroundTableEnd(builder)
