# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BattleBGM(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BattleBGM()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBattleBGM(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BattleBGM
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BattleBGM
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def TypeValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def Grade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def TitleSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def ArrangeSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def ItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleBGM
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BattleBGM
    def BgmName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BattleBGMStart(builder):
    builder.StartObject(9)

def Start(builder):
    BattleBGMStart(builder)

def BattleBGMAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    BattleBGMAddNo(builder, no)

def BattleBGMAddType(builder, type):
    builder.PrependInt32Slot(1, type, 0)

def AddType(builder, type):
    BattleBGMAddType(builder, type)

def BattleBGMAddTypeValue(builder, typeValue):
    builder.PrependInt32Slot(2, typeValue, 0)

def AddTypeValue(builder, typeValue):
    BattleBGMAddTypeValue(builder, typeValue)

def BattleBGMAddGrade(builder, grade):
    builder.PrependInt32Slot(3, grade, 0)

def AddGrade(builder, grade):
    BattleBGMAddGrade(builder, grade)

def BattleBGMAddTitleSno(builder, titleSno):
    builder.PrependInt32Slot(4, titleSno, 0)

def AddTitleSno(builder, titleSno):
    BattleBGMAddTitleSno(builder, titleSno)

def BattleBGMAddArrangeSno(builder, arrangeSno):
    builder.PrependInt32Slot(5, arrangeSno, 0)

def AddArrangeSno(builder, arrangeSno):
    BattleBGMAddArrangeSno(builder, arrangeSno)

def BattleBGMAddItemNo(builder, itemNo):
    builder.PrependInt32Slot(6, itemNo, 0)

def AddItemNo(builder, itemNo):
    BattleBGMAddItemNo(builder, itemNo)

def BattleBGMAddImagePath(builder, imagePath):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(imagePath), 0)

def AddImagePath(builder, imagePath):
    BattleBGMAddImagePath(builder, imagePath)

def BattleBGMAddBgmName(builder, bgmName):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(bgmName), 0)

def AddBgmName(builder, bgmName):
    BattleBGMAddBgmName(builder, bgmName)

def BattleBGMEnd(builder):
    return builder.EndObject()

def End(builder):
    return BattleBGMEnd(builder)
