# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CashShopHeroPass(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CashShopHeroPass()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCashShopHeroPass(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CashShopHeroPass
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CashShopHeroPass
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CashShopHeroPass
    def ShopNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CashShopHeroPass
    def HeroNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CashShopHeroPass
    def HeroImagePosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CashShopHeroPassStart(builder):
    builder.StartObject(4)

def Start(builder):
    CashShopHeroPassStart(builder)

def CashShopHeroPassAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    CashShopHeroPassAddNo(builder, no)

def CashShopHeroPassAddShopNo(builder, shopNo):
    builder.PrependInt32Slot(1, shopNo, 0)

def AddShopNo(builder, shopNo):
    CashShopHeroPassAddShopNo(builder, shopNo)

def CashShopHeroPassAddHeroNo(builder, heroNo):
    builder.PrependInt32Slot(2, heroNo, 0)

def AddHeroNo(builder, heroNo):
    CashShopHeroPassAddHeroNo(builder, heroNo)

def CashShopHeroPassAddHeroImagePosition(builder, heroImagePosition):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(heroImagePosition), 0)

def AddHeroImagePosition(builder, heroImagePosition):
    CashShopHeroPassAddHeroImagePosition(builder, heroImagePosition)

def CashShopHeroPassEnd(builder):
    return builder.EndObject()

def End(builder):
    return CashShopHeroPassEnd(builder)
