# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CashShopUITable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CashShopUITable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCashShopUITable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CashShopUITable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CashShopUITable
    def CashShopUIs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.CashShopUI import CashShopUI
            obj = CashShopUI()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CashShopUITable
    def CashShopUIsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CashShopUITable
    def CashShopUIsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CashShopUITableStart(builder):
    builder.StartObject(1)

def Start(builder):
    CashShopUITableStart(builder)

def CashShopUITableAddCashShopUIs(builder, cashShopUIs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cashShopUIs), 0)

def AddCashShopUIs(builder, cashShopUIs):
    CashShopUITableAddCashShopUIs(builder, cashShopUIs)

def CashShopUITableStartCashShopUIsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCashShopUIsVector(builder, numElems):
    return CashShopUITableStartCashShopUIsVector(builder, numElems)

def CashShopUITableEnd(builder):
    return builder.EndObject()

def End(builder):
    return CashShopUITableEnd(builder)
