# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ContentsLimit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContentsLimit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContentsLimit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ContentsLimit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContentsLimit
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ContentsLimit
    def CheckStageNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ContentsLimit
    def NameStringSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ContentsLimitStart(builder):
    builder.StartObject(3)

def Start(builder):
    ContentsLimitStart(builder)

def ContentsLimitAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    ContentsLimitAddNo(builder, no)

def ContentsLimitAddCheckStageNo(builder, checkStageNo):
    builder.PrependInt32Slot(1, checkStageNo, 0)

def AddCheckStageNo(builder, checkStageNo):
    ContentsLimitAddCheckStageNo(builder, checkStageNo)

def ContentsLimitAddNameStringSno(builder, nameStringSno):
    builder.PrependInt32Slot(2, nameStringSno, 0)

def AddNameStringSno(builder, nameStringSno):
    ContentsLimitAddNameStringSno(builder, nameStringSno)

def ContentsLimitEnd(builder):
    return builder.EndObject()

def End(builder):
    return ContentsLimitEnd(builder)
