# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DefaultProfileSetting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DefaultProfileSetting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDefaultProfileSetting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DefaultProfileSetting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DefaultProfileSetting
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DefaultProfileSetting
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DefaultProfileSetting
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DefaultProfileSetting
    def NameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DefaultProfileSetting
    def PanelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DefaultProfileSetting
    def ContentsLimitNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DefaultProfileSettingStart(builder):
    builder.StartObject(6)

def Start(builder):
    DefaultProfileSettingStart(builder)

def DefaultProfileSettingAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    DefaultProfileSettingAddNo(builder, no)

def DefaultProfileSettingAddType(builder, type):
    builder.PrependInt32Slot(1, type, 0)

def AddType(builder, type):
    DefaultProfileSettingAddType(builder, type)

def DefaultProfileSettingAddIndex(builder, index):
    builder.PrependInt32Slot(2, index, 0)

def AddIndex(builder, index):
    DefaultProfileSettingAddIndex(builder, index)

def DefaultProfileSettingAddNameSno(builder, nameSno):
    builder.PrependInt32Slot(3, nameSno, 0)

def AddNameSno(builder, nameSno):
    DefaultProfileSettingAddNameSno(builder, nameSno)

def DefaultProfileSettingAddPanelType(builder, panelType):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(panelType), 0)

def AddPanelType(builder, panelType):
    DefaultProfileSettingAddPanelType(builder, panelType)

def DefaultProfileSettingAddContentsLimitNo(builder, contentsLimitNo):
    builder.PrependInt32Slot(5, contentsLimitNo, 0)

def AddContentsLimitNo(builder, contentsLimitNo):
    DefaultProfileSettingAddContentsLimitNo(builder, contentsLimitNo)

def DefaultProfileSettingEnd(builder):
    return builder.EndObject()

def End(builder):
    return DefaultProfileSettingEnd(builder)
