# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DoubleGateBuff(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DoubleGateBuff()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDoubleGateBuff(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DoubleGateBuff
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DoubleGateBuff
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DoubleGateBuff
    def BuffGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DoubleGateBuff
    def BuffNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DoubleGateBuff
    def BuffNameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DoubleGateBuff
    def BuffTooltipSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DoubleGateBuffStart(builder):
    builder.StartObject(5)

def Start(builder):
    DoubleGateBuffStart(builder)

def DoubleGateBuffAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    DoubleGateBuffAddNo(builder, no)

def DoubleGateBuffAddBuffGroup(builder, buffGroup):
    builder.PrependInt32Slot(1, buffGroup, 0)

def AddBuffGroup(builder, buffGroup):
    DoubleGateBuffAddBuffGroup(builder, buffGroup)

def DoubleGateBuffAddBuffNo(builder, buffNo):
    builder.PrependInt32Slot(2, buffNo, 0)

def AddBuffNo(builder, buffNo):
    DoubleGateBuffAddBuffNo(builder, buffNo)

def DoubleGateBuffAddBuffNameSno(builder, buffNameSno):
    builder.PrependInt32Slot(3, buffNameSno, 0)

def AddBuffNameSno(builder, buffNameSno):
    DoubleGateBuffAddBuffNameSno(builder, buffNameSno)

def DoubleGateBuffAddBuffTooltipSno(builder, buffTooltipSno):
    builder.PrependInt32Slot(4, buffTooltipSno, 0)

def AddBuffTooltipSno(builder, buffTooltipSno):
    DoubleGateBuffAddBuffTooltipSno(builder, buffTooltipSno)

def DoubleGateBuffEnd(builder):
    return builder.EndObject()

def End(builder):
    return DoubleGateBuffEnd(builder)
