# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonTrainingRewardTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonTrainingRewardTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonTrainingRewardTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonTrainingRewardTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonTrainingRewardTable
    def DungeonTrainingRewards(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.DungeonTrainingReward import DungeonTrainingReward
            obj = DungeonTrainingReward()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DungeonTrainingRewardTable
    def DungeonTrainingRewardsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DungeonTrainingRewardTable
    def DungeonTrainingRewardsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DungeonTrainingRewardTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    DungeonTrainingRewardTableStart(builder)

def DungeonTrainingRewardTableAddDungeonTrainingRewards(builder, dungeonTrainingRewards):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dungeonTrainingRewards), 0)

def AddDungeonTrainingRewards(builder, dungeonTrainingRewards):
    DungeonTrainingRewardTableAddDungeonTrainingRewards(builder, dungeonTrainingRewards)

def DungeonTrainingRewardTableStartDungeonTrainingRewardsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDungeonTrainingRewardsVector(builder, numElems):
    return DungeonTrainingRewardTableStartDungeonTrainingRewardsVector(builder, numElems)

def DungeonTrainingRewardTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonTrainingRewardTableEnd(builder)
