# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonDifficultyTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonDifficultyTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonDifficultyTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonDifficultyTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonDifficultyTable
    def DungeonDifficultys(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.DungeonDifficulty import DungeonDifficulty
            obj = DungeonDifficulty()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DungeonDifficultyTable
    def DungeonDifficultysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DungeonDifficultyTable
    def DungeonDifficultysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DungeonDifficultyTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    DungeonDifficultyTableStart(builder)

def DungeonDifficultyTableAddDungeonDifficultys(builder, dungeonDifficultys):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dungeonDifficultys), 0)

def AddDungeonDifficultys(builder, dungeonDifficultys):
    DungeonDifficultyTableAddDungeonDifficultys(builder, dungeonDifficultys)

def DungeonDifficultyTableStartDungeonDifficultysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDungeonDifficultysVector(builder, numElems):
    return DungeonDifficultyTableStartDungeonDifficultysVector(builder, numElems)

def DungeonDifficultyTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonDifficultyTableEnd(builder)
