# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonRelic(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonRelic()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonRelic(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonRelic
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonRelic
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def EffectType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def GradeSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def BuffGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def BattlebuffNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def RelicType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def SetNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def EnhanceNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def EffectBuff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def BuffValue1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DungeonRelic
    def BuffValue2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DungeonRelic
    def IconImg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DungeonRelic
    def NameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def DescSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonRelic
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DungeonRelicStart(builder):
    builder.StartObject(16)

def Start(builder):
    DungeonRelicStart(builder)

def DungeonRelicAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    DungeonRelicAddNo(builder, no)

def DungeonRelicAddGroup(builder, group):
    builder.PrependInt32Slot(1, group, 0)

def AddGroup(builder, group):
    DungeonRelicAddGroup(builder, group)

def DungeonRelicAddEffectType(builder, effectType):
    builder.PrependInt32Slot(2, effectType, 0)

def AddEffectType(builder, effectType):
    DungeonRelicAddEffectType(builder, effectType)

def DungeonRelicAddGradeSno(builder, gradeSno):
    builder.PrependInt32Slot(3, gradeSno, 0)

def AddGradeSno(builder, gradeSno):
    DungeonRelicAddGradeSno(builder, gradeSno)

def DungeonRelicAddBuffGroup(builder, buffGroup):
    builder.PrependInt32Slot(4, buffGroup, 0)

def AddBuffGroup(builder, buffGroup):
    DungeonRelicAddBuffGroup(builder, buffGroup)

def DungeonRelicAddBattlebuffNo(builder, battlebuffNo):
    builder.PrependInt32Slot(5, battlebuffNo, 0)

def AddBattlebuffNo(builder, battlebuffNo):
    DungeonRelicAddBattlebuffNo(builder, battlebuffNo)

def DungeonRelicAddRelicType(builder, relicType):
    builder.PrependInt32Slot(6, relicType, 0)

def AddRelicType(builder, relicType):
    DungeonRelicAddRelicType(builder, relicType)

def DungeonRelicAddSetNo(builder, setNo):
    builder.PrependInt32Slot(7, setNo, 0)

def AddSetNo(builder, setNo):
    DungeonRelicAddSetNo(builder, setNo)

def DungeonRelicAddEnhanceNo(builder, enhanceNo):
    builder.PrependInt32Slot(8, enhanceNo, 0)

def AddEnhanceNo(builder, enhanceNo):
    DungeonRelicAddEnhanceNo(builder, enhanceNo)

def DungeonRelicAddEffectBuff(builder, effectBuff):
    builder.PrependInt32Slot(9, effectBuff, 0)

def AddEffectBuff(builder, effectBuff):
    DungeonRelicAddEffectBuff(builder, effectBuff)

def DungeonRelicAddBuffValue1(builder, buffValue1):
    builder.PrependFloat32Slot(10, buffValue1, 0.0)

def AddBuffValue1(builder, buffValue1):
    DungeonRelicAddBuffValue1(builder, buffValue1)

def DungeonRelicAddBuffValue2(builder, buffValue2):
    builder.PrependFloat32Slot(11, buffValue2, 0.0)

def AddBuffValue2(builder, buffValue2):
    DungeonRelicAddBuffValue2(builder, buffValue2)

def DungeonRelicAddIconImg(builder, iconImg):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(iconImg), 0)

def AddIconImg(builder, iconImg):
    DungeonRelicAddIconImg(builder, iconImg)

def DungeonRelicAddNameSno(builder, nameSno):
    builder.PrependInt32Slot(13, nameSno, 0)

def AddNameSno(builder, nameSno):
    DungeonRelicAddNameSno(builder, nameSno)

def DungeonRelicAddDescSno(builder, descSno):
    builder.PrependInt32Slot(14, descSno, 0)

def AddDescSno(builder, descSno):
    DungeonRelicAddDescSno(builder, descSno)

def DungeonRelicAddWeight(builder, weight):
    builder.PrependInt32Slot(15, weight, 0)

def AddWeight(builder, weight):
    DungeonRelicAddWeight(builder, weight)

def DungeonRelicEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonRelicEnd(builder)
