# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonChestRewardTrainingTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonChestRewardTrainingTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonChestRewardTrainingTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonChestRewardTrainingTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonChestRewardTrainingTable
    def DungeonChestRewardTrainings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.DungeonChestRewardTraining import DungeonChestRewardTraining
            obj = DungeonChestRewardTraining()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DungeonChestRewardTrainingTable
    def DungeonChestRewardTrainingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DungeonChestRewardTrainingTable
    def DungeonChestRewardTrainingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DungeonChestRewardTrainingTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    DungeonChestRewardTrainingTableStart(builder)

def DungeonChestRewardTrainingTableAddDungeonChestRewardTrainings(builder, dungeonChestRewardTrainings):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dungeonChestRewardTrainings), 0)

def AddDungeonChestRewardTrainings(builder, dungeonChestRewardTrainings):
    DungeonChestRewardTrainingTableAddDungeonChestRewardTrainings(builder, dungeonChestRewardTrainings)

def DungeonChestRewardTrainingTableStartDungeonChestRewardTrainingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDungeonChestRewardTrainingsVector(builder, numElems):
    return DungeonChestRewardTrainingTableStartDungeonChestRewardTrainingsVector(builder, numElems)

def DungeonChestRewardTrainingTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonChestRewardTrainingTableEnd(builder)
