# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonLevelScale(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonLevelScale()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonLevelScale(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonLevelScale
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonLevelScale
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonLevelScale
    def GroupNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonLevelScale
    def MonsterType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DungeonLevelScale
    def MonsterAddLevelMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonLevelScale
    def MonsterAddLevelMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DungeonLevelScaleStart(builder):
    builder.StartObject(5)

def Start(builder):
    DungeonLevelScaleStart(builder)

def DungeonLevelScaleAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    DungeonLevelScaleAddNo(builder, no)

def DungeonLevelScaleAddGroupNo(builder, groupNo):
    builder.PrependInt32Slot(1, groupNo, 0)

def AddGroupNo(builder, groupNo):
    DungeonLevelScaleAddGroupNo(builder, groupNo)

def DungeonLevelScaleAddMonsterType(builder, monsterType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(monsterType), 0)

def AddMonsterType(builder, monsterType):
    DungeonLevelScaleAddMonsterType(builder, monsterType)

def DungeonLevelScaleAddMonsterAddLevelMin(builder, monsterAddLevelMin):
    builder.PrependInt32Slot(3, monsterAddLevelMin, 0)

def AddMonsterAddLevelMin(builder, monsterAddLevelMin):
    DungeonLevelScaleAddMonsterAddLevelMin(builder, monsterAddLevelMin)

def DungeonLevelScaleAddMonsterAddLevelMax(builder, monsterAddLevelMax):
    builder.PrependInt32Slot(4, monsterAddLevelMax, 0)

def AddMonsterAddLevelMax(builder, monsterAddLevelMax):
    DungeonLevelScaleAddMonsterAddLevelMax(builder, monsterAddLevelMax)

def DungeonLevelScaleEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonLevelScaleEnd(builder)
