# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DungeonBlock(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DungeonBlock()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDungeonBlock(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DungeonBlock
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DungeonBlock
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonBlock
    def DungeonType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DungeonBlock
    def StartDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DungeonBlock
    def EndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DungeonBlockStart(builder):
    builder.StartObject(4)

def Start(builder):
    DungeonBlockStart(builder)

def DungeonBlockAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    DungeonBlockAddNo(builder, no)

def DungeonBlockAddDungeonType(builder, dungeonType):
    builder.PrependInt32Slot(1, dungeonType, 0)

def AddDungeonType(builder, dungeonType):
    DungeonBlockAddDungeonType(builder, dungeonType)

def DungeonBlockAddStartDate(builder, startDate):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(startDate), 0)

def AddStartDate(builder, startDate):
    DungeonBlockAddStartDate(builder, startDate)

def DungeonBlockAddEndDate(builder, endDate):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(endDate), 0)

def AddEndDate(builder, endDate):
    DungeonBlockAddEndDate(builder, endDate)

def DungeonBlockEnd(builder):
    return builder.EndObject()

def End(builder):
    return DungeonBlockEnd(builder)
