# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenUnionConstraintScheduleTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenUnionConstraintScheduleTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenUnionConstraintScheduleTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenUnionConstraintScheduleTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenUnionConstraintScheduleTable
    def EdenUnionConstraintSchedules(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EdenUnionConstraintSchedule import EdenUnionConstraintSchedule
            obj = EdenUnionConstraintSchedule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EdenUnionConstraintScheduleTable
    def EdenUnionConstraintSchedulesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EdenUnionConstraintScheduleTable
    def EdenUnionConstraintSchedulesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EdenUnionConstraintScheduleTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EdenUnionConstraintScheduleTableStart(builder)

def EdenUnionConstraintScheduleTableAddEdenUnionConstraintSchedules(builder, edenUnionConstraintSchedules):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edenUnionConstraintSchedules), 0)

def AddEdenUnionConstraintSchedules(builder, edenUnionConstraintSchedules):
    EdenUnionConstraintScheduleTableAddEdenUnionConstraintSchedules(builder, edenUnionConstraintSchedules)

def EdenUnionConstraintScheduleTableStartEdenUnionConstraintSchedulesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdenUnionConstraintSchedulesVector(builder, numElems):
    return EdenUnionConstraintScheduleTableStartEdenUnionConstraintSchedulesVector(builder, numElems)

def EdenUnionConstraintScheduleTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenUnionConstraintScheduleTableEnd(builder)
