# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenAllianceStageBattleTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenAllianceStageBattleTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenAllianceStageBattleTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenAllianceStageBattleTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenAllianceStageBattleTable
    def EdenAllianceStageBattles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EdenAllianceStageBattle import EdenAllianceStageBattle
            obj = EdenAllianceStageBattle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EdenAllianceStageBattleTable
    def EdenAllianceStageBattlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EdenAllianceStageBattleTable
    def EdenAllianceStageBattlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EdenAllianceStageBattleTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EdenAllianceStageBattleTableStart(builder)

def EdenAllianceStageBattleTableAddEdenAllianceStageBattles(builder, edenAllianceStageBattles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edenAllianceStageBattles), 0)

def AddEdenAllianceStageBattles(builder, edenAllianceStageBattles):
    EdenAllianceStageBattleTableAddEdenAllianceStageBattles(builder, edenAllianceStageBattles)

def EdenAllianceStageBattleTableStartEdenAllianceStageBattlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdenAllianceStageBattlesVector(builder, numElems):
    return EdenAllianceStageBattleTableStartEdenAllianceStageBattlesVector(builder, numElems)

def EdenAllianceStageBattleTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenAllianceStageBattleTableEnd(builder)
