# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenAlliancePointTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenAlliancePointTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenAlliancePointTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenAlliancePointTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenAlliancePointTable
    def EdenAlliancePoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EdenAlliancePoint import EdenAlliancePoint
            obj = EdenAlliancePoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EdenAlliancePointTable
    def EdenAlliancePointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EdenAlliancePointTable
    def EdenAlliancePointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EdenAlliancePointTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EdenAlliancePointTableStart(builder)

def EdenAlliancePointTableAddEdenAlliancePoints(builder, edenAlliancePoints):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edenAlliancePoints), 0)

def AddEdenAlliancePoints(builder, edenAlliancePoints):
    EdenAlliancePointTableAddEdenAlliancePoints(builder, edenAlliancePoints)

def EdenAlliancePointTableStartEdenAlliancePointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdenAlliancePointsVector(builder, numElems):
    return EdenAlliancePointTableStartEdenAlliancePointsVector(builder, numElems)

def EdenAlliancePointTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenAlliancePointTableEnd(builder)
