# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenUnion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenUnion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenUnion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenUnion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenUnion
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def ScheduleKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EdenUnion
    def UnionGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def UnionRankGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def UnionRankConstraintCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def StageNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def NameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def StoryNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def BgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EdenUnion
    def SoundPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EdenUnion
    def EmblemPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EdenUnion
    def DailyReward(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def RewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenUnion
    def ProfileView(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EdenUnionStart(builder):
    builder.StartObject(14)

def Start(builder):
    EdenUnionStart(builder)

def EdenUnionAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EdenUnionAddNo(builder, no)

def EdenUnionAddScheduleKey(builder, scheduleKey):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(scheduleKey), 0)

def AddScheduleKey(builder, scheduleKey):
    EdenUnionAddScheduleKey(builder, scheduleKey)

def EdenUnionAddUnionGroup(builder, unionGroup):
    builder.PrependInt32Slot(2, unionGroup, 0)

def AddUnionGroup(builder, unionGroup):
    EdenUnionAddUnionGroup(builder, unionGroup)

def EdenUnionAddUnionRankGroup(builder, unionRankGroup):
    builder.PrependInt32Slot(3, unionRankGroup, 0)

def AddUnionRankGroup(builder, unionRankGroup):
    EdenUnionAddUnionRankGroup(builder, unionRankGroup)

def EdenUnionAddUnionRankConstraintCount(builder, unionRankConstraintCount):
    builder.PrependInt32Slot(4, unionRankConstraintCount, 0)

def AddUnionRankConstraintCount(builder, unionRankConstraintCount):
    EdenUnionAddUnionRankConstraintCount(builder, unionRankConstraintCount)

def EdenUnionAddStageNo(builder, stageNo):
    builder.PrependInt32Slot(5, stageNo, 0)

def AddStageNo(builder, stageNo):
    EdenUnionAddStageNo(builder, stageNo)

def EdenUnionAddNameSno(builder, nameSno):
    builder.PrependInt32Slot(6, nameSno, 0)

def AddNameSno(builder, nameSno):
    EdenUnionAddNameSno(builder, nameSno)

def EdenUnionAddStoryNo(builder, storyNo):
    builder.PrependInt32Slot(7, storyNo, 0)

def AddStoryNo(builder, storyNo):
    EdenUnionAddStoryNo(builder, storyNo)

def EdenUnionAddBgPath(builder, bgPath):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(bgPath), 0)

def AddBgPath(builder, bgPath):
    EdenUnionAddBgPath(builder, bgPath)

def EdenUnionAddSoundPath(builder, soundPath):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(soundPath), 0)

def AddSoundPath(builder, soundPath):
    EdenUnionAddSoundPath(builder, soundPath)

def EdenUnionAddEmblemPath(builder, emblemPath):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(emblemPath), 0)

def AddEmblemPath(builder, emblemPath):
    EdenUnionAddEmblemPath(builder, emblemPath)

def EdenUnionAddDailyReward(builder, dailyReward):
    builder.PrependInt32Slot(11, dailyReward, 0)

def AddDailyReward(builder, dailyReward):
    EdenUnionAddDailyReward(builder, dailyReward)

def EdenUnionAddRewardAmount(builder, rewardAmount):
    builder.PrependInt32Slot(12, rewardAmount, 0)

def AddRewardAmount(builder, rewardAmount):
    EdenUnionAddRewardAmount(builder, rewardAmount)

def EdenUnionAddProfileView(builder, profileView):
    builder.PrependInt32Slot(13, profileView, 0)

def AddProfileView(builder, profileView):
    EdenUnionAddProfileView(builder, profileView)

def EdenUnionEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenUnionEnd(builder)
