# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenUnionMissionTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenUnionMissionTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenUnionMissionTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenUnionMissionTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenUnionMissionTable
    def EdenUnionMissions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EdenUnionMission import EdenUnionMission
            obj = EdenUnionMission()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EdenUnionMissionTable
    def EdenUnionMissionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EdenUnionMissionTable
    def EdenUnionMissionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EdenUnionMissionTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EdenUnionMissionTableStart(builder)

def EdenUnionMissionTableAddEdenUnionMissions(builder, edenUnionMissions):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edenUnionMissions), 0)

def AddEdenUnionMissions(builder, edenUnionMissions):
    EdenUnionMissionTableAddEdenUnionMissions(builder, edenUnionMissions)

def EdenUnionMissionTableStartEdenUnionMissionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdenUnionMissionsVector(builder, numElems):
    return EdenUnionMissionTableStartEdenUnionMissionsVector(builder, numElems)

def EdenUnionMissionTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenUnionMissionTableEnd(builder)
