# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EdenAllianceTier(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EdenAllianceTier()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdenAllianceTier(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EdenAllianceTier
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EdenAllianceTier
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenAllianceTier
    def TierNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenAllianceTier
    def RankStandard(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # EdenAllianceTier
    def TierStringNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EdenAllianceTier
    def TierPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EdenAllianceTierStart(builder):
    builder.StartObject(5)

def Start(builder):
    EdenAllianceTierStart(builder)

def EdenAllianceTierAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EdenAllianceTierAddNo(builder, no)

def EdenAllianceTierAddTierNo(builder, tierNo):
    builder.PrependInt32Slot(1, tierNo, 0)

def AddTierNo(builder, tierNo):
    EdenAllianceTierAddTierNo(builder, tierNo)

def EdenAllianceTierAddRankStandard(builder, rankStandard):
    builder.PrependFloat32Slot(2, rankStandard, 0.0)

def AddRankStandard(builder, rankStandard):
    EdenAllianceTierAddRankStandard(builder, rankStandard)

def EdenAllianceTierAddTierStringNo(builder, tierStringNo):
    builder.PrependInt32Slot(3, tierStringNo, 0)

def AddTierStringNo(builder, tierStringNo):
    EdenAllianceTierAddTierStringNo(builder, tierStringNo)

def EdenAllianceTierAddTierPath(builder, tierPath):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(tierPath), 0)

def AddTierPath(builder, tierPath):
    EdenAllianceTierAddTierPath(builder, tierPath)

def EdenAllianceTierEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdenAllianceTierEnd(builder)
