# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventRankRaidTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventRankRaidTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventRankRaidTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventRankRaidTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventRankRaidTable
    def EventRankRaids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventRankRaid import EventRankRaid
            obj = EventRankRaid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventRankRaidTable
    def EventRankRaidsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventRankRaidTable
    def EventRankRaidsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventRankRaidTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventRankRaidTableStart(builder)

def EventRankRaidTableAddEventRankRaids(builder, eventRankRaids):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventRankRaids), 0)

def AddEventRankRaids(builder, eventRankRaids):
    EventRankRaidTableAddEventRankRaids(builder, eventRankRaids)

def EventRankRaidTableStartEventRankRaidsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventRankRaidsVector(builder, numElems):
    return EventRankRaidTableStartEventRankRaidsVector(builder, numElems)

def EventRankRaidTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventRankRaidTableEnd(builder)
