# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventSelectStageSettingTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventSelectStageSettingTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventSelectStageSettingTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventSelectStageSettingTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventSelectStageSettingTable
    def EventSelectStageSettings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventSelectStageSetting import EventSelectStageSetting
            obj = EventSelectStageSetting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventSelectStageSettingTable
    def EventSelectStageSettingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventSelectStageSettingTable
    def EventSelectStageSettingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventSelectStageSettingTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventSelectStageSettingTableStart(builder)

def EventSelectStageSettingTableAddEventSelectStageSettings(builder, eventSelectStageSettings):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventSelectStageSettings), 0)

def AddEventSelectStageSettings(builder, eventSelectStageSettings):
    EventSelectStageSettingTableAddEventSelectStageSettings(builder, eventSelectStageSettings)

def EventSelectStageSettingTableStartEventSelectStageSettingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventSelectStageSettingsVector(builder, numElems):
    return EventSelectStageSettingTableStartEventSelectStageSettingsVector(builder, numElems)

def EventSelectStageSettingTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventSelectStageSettingTableEnd(builder)
