# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventBossRushReward(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventBossRushReward()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventBossRushReward(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventBossRushReward
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventBossRushReward
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventBossRushReward
    def DungeonNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventBossRushReward
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventBossRushReward
    def RewardType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventBossRushReward
    def RewardNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventBossRushReward
    def RewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventBossRushRewardStart(builder):
    builder.StartObject(6)

def Start(builder):
    EventBossRushRewardStart(builder)

def EventBossRushRewardAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    EventBossRushRewardAddId(builder, id)

def EventBossRushRewardAddDungeonNo(builder, dungeonNo):
    builder.PrependInt32Slot(1, dungeonNo, 0)

def AddDungeonNo(builder, dungeonNo):
    EventBossRushRewardAddDungeonNo(builder, dungeonNo)

def EventBossRushRewardAddLevel(builder, level):
    builder.PrependInt32Slot(2, level, 0)

def AddLevel(builder, level):
    EventBossRushRewardAddLevel(builder, level)

def EventBossRushRewardAddRewardType(builder, rewardType):
    builder.PrependInt32Slot(3, rewardType, 0)

def AddRewardType(builder, rewardType):
    EventBossRushRewardAddRewardType(builder, rewardType)

def EventBossRushRewardAddRewardNo(builder, rewardNo):
    builder.PrependInt32Slot(4, rewardNo, 0)

def AddRewardNo(builder, rewardNo):
    EventBossRushRewardAddRewardNo(builder, rewardNo)

def EventBossRushRewardAddRewardAmount(builder, rewardAmount):
    builder.PrependInt32Slot(5, rewardAmount, 0)

def AddRewardAmount(builder, rewardAmount):
    EventBossRushRewardAddRewardAmount(builder, rewardAmount)

def EventBossRushRewardEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventBossRushRewardEnd(builder)
