# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventAttendance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventAttendance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventAttendance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventAttendance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventAttendance
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def AttendanceOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def RewardItem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def RewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def BuyAttendOpen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventAttendance
    def BuyAttendCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventAttendanceStart(builder):
    builder.StartObject(7)

def Start(builder):
    EventAttendanceStart(builder)

def EventAttendanceAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventAttendanceAddNo(builder, no)

def EventAttendanceAddGroup(builder, group):
    builder.PrependInt32Slot(1, group, 0)

def AddGroup(builder, group):
    EventAttendanceAddGroup(builder, group)

def EventAttendanceAddAttendanceOrder(builder, attendanceOrder):
    builder.PrependInt32Slot(2, attendanceOrder, 0)

def AddAttendanceOrder(builder, attendanceOrder):
    EventAttendanceAddAttendanceOrder(builder, attendanceOrder)

def EventAttendanceAddRewardItem(builder, rewardItem):
    builder.PrependInt32Slot(3, rewardItem, 0)

def AddRewardItem(builder, rewardItem):
    EventAttendanceAddRewardItem(builder, rewardItem)

def EventAttendanceAddRewardAmount(builder, rewardAmount):
    builder.PrependInt32Slot(4, rewardAmount, 0)

def AddRewardAmount(builder, rewardAmount):
    EventAttendanceAddRewardAmount(builder, rewardAmount)

def EventAttendanceAddBuyAttendOpen(builder, buyAttendOpen):
    builder.PrependInt32Slot(5, buyAttendOpen, 0)

def AddBuyAttendOpen(builder, buyAttendOpen):
    EventAttendanceAddBuyAttendOpen(builder, buyAttendOpen)

def EventAttendanceAddBuyAttendCost(builder, buyAttendCost):
    builder.PrependInt32Slot(6, buyAttendCost, 0)

def AddBuyAttendCost(builder, buyAttendCost):
    EventAttendanceAddBuyAttendCost(builder, buyAttendCost)

def EventAttendanceEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventAttendanceEnd(builder)
