# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDefensePlayerSetting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDefensePlayerSetting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDefensePlayerSetting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDefensePlayerSetting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDefensePlayerSetting
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefensePlayerSetting
    def UserLevelValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefensePlayerSetting
    def CharacterHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefensePlayerSetting
    def CharacterDamage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventDefensePlayerSetting
    def Exp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventDefensePlayerSettingStart(builder):
    builder.StartObject(5)

def Start(builder):
    EventDefensePlayerSettingStart(builder)

def EventDefensePlayerSettingAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventDefensePlayerSettingAddNo(builder, no)

def EventDefensePlayerSettingAddUserLevelValue(builder, userLevelValue):
    builder.PrependInt32Slot(1, userLevelValue, 0)

def AddUserLevelValue(builder, userLevelValue):
    EventDefensePlayerSettingAddUserLevelValue(builder, userLevelValue)

def EventDefensePlayerSettingAddCharacterHp(builder, characterHp):
    builder.PrependInt32Slot(2, characterHp, 0)

def AddCharacterHp(builder, characterHp):
    EventDefensePlayerSettingAddCharacterHp(builder, characterHp)

def EventDefensePlayerSettingAddCharacterDamage(builder, characterDamage):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(characterDamage), 0)

def AddCharacterDamage(builder, characterDamage):
    EventDefensePlayerSettingAddCharacterDamage(builder, characterDamage)

def EventDefensePlayerSettingAddExp(builder, exp):
    builder.PrependInt32Slot(4, exp, 0)

def AddExp(builder, exp):
    EventDefensePlayerSettingAddExp(builder, exp)

def EventDefensePlayerSettingEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDefensePlayerSettingEnd(builder)
