# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDiceGoalPoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDiceGoalPoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDiceGoalPoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDiceGoalPoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDiceGoalPoint
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDiceGoalPoint
    def GoalPointGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDiceGoalPoint
    def IsRepeat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDiceGoalPoint
    def GoalNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDiceGoalPoint
    def RewardPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventDiceGoalPointStart(builder):
    builder.StartObject(5)

def Start(builder):
    EventDiceGoalPointStart(builder)

def EventDiceGoalPointAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventDiceGoalPointAddNo(builder, no)

def EventDiceGoalPointAddGoalPointGroup(builder, goalPointGroup):
    builder.PrependInt32Slot(1, goalPointGroup, 0)

def AddGoalPointGroup(builder, goalPointGroup):
    EventDiceGoalPointAddGoalPointGroup(builder, goalPointGroup)

def EventDiceGoalPointAddIsRepeat(builder, isRepeat):
    builder.PrependInt32Slot(2, isRepeat, 0)

def AddIsRepeat(builder, isRepeat):
    EventDiceGoalPointAddIsRepeat(builder, isRepeat)

def EventDiceGoalPointAddGoalNo(builder, goalNo):
    builder.PrependInt32Slot(3, goalNo, 0)

def AddGoalNo(builder, goalNo):
    EventDiceGoalPointAddGoalNo(builder, goalNo)

def EventDiceGoalPointAddRewardPoint(builder, rewardPoint):
    builder.PrependInt32Slot(4, rewardPoint, 0)

def AddRewardPoint(builder, rewardPoint):
    EventDiceGoalPointAddRewardPoint(builder, rewardPoint)

def EventDiceGoalPointEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDiceGoalPointEnd(builder)
