# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDefenseInfoTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDefenseInfoTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDefenseInfoTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDefenseInfoTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDefenseInfoTable
    def EventDefenseInfos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventDefenseInfo import EventDefenseInfo
            obj = EventDefenseInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventDefenseInfoTable
    def EventDefenseInfosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventDefenseInfoTable
    def EventDefenseInfosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventDefenseInfoTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventDefenseInfoTableStart(builder)

def EventDefenseInfoTableAddEventDefenseInfos(builder, eventDefenseInfos):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventDefenseInfos), 0)

def AddEventDefenseInfos(builder, eventDefenseInfos):
    EventDefenseInfoTableAddEventDefenseInfos(builder, eventDefenseInfos)

def EventDefenseInfoTableStartEventDefenseInfosVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventDefenseInfosVector(builder, numElems):
    return EventDefenseInfoTableStartEventDefenseInfosVector(builder, numElems)

def EventDefenseInfoTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDefenseInfoTableEnd(builder)
