# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDiceSlotTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDiceSlotTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDiceSlotTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDiceSlotTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDiceSlotTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventDiceSlot import EventDiceSlot
            obj = EventDiceSlot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventDiceSlotTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventDiceSlotTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventDiceSlotTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventDiceSlotTableStart(builder)

def EventDiceSlotTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    EventDiceSlotTableAddJson(builder, json)

def EventDiceSlotTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return EventDiceSlotTableStartJsonVector(builder, numElems)

def EventDiceSlotTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDiceSlotTableEnd(builder)
