# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDefenseEnemySetting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDefenseEnemySetting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDefenseEnemySetting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDefenseEnemySetting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDefenseEnemySetting
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def EventGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def PrefabPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventDefenseEnemySetting
    def TimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventDefenseEnemySetting
    def TimelineName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventDefenseEnemySetting
    def ModelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def UseBossSlot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def MonsterType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def MonsterMoveType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def MaxCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def Movedelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def Movespeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def MonsterAtk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def MonsterHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def SpawnStartTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def SpawnEndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def SpawnPerSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def SpawnAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def Exp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def ItemDropProb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDefenseEnemySetting
    def ItemDropList(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EventDefenseEnemySettingStart(builder):
    builder.StartObject(23)

def Start(builder):
    EventDefenseEnemySettingStart(builder)

def EventDefenseEnemySettingAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventDefenseEnemySettingAddNo(builder, no)

def EventDefenseEnemySettingAddEventGroup(builder, eventGroup):
    builder.PrependInt32Slot(1, eventGroup, 0)

def AddEventGroup(builder, eventGroup):
    EventDefenseEnemySettingAddEventGroup(builder, eventGroup)

def EventDefenseEnemySettingAddPrefabPath(builder, prefabPath):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prefabPath), 0)

def AddPrefabPath(builder, prefabPath):
    EventDefenseEnemySettingAddPrefabPath(builder, prefabPath)

def EventDefenseEnemySettingAddTimelinePath(builder, timelinePath):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timelinePath), 0)

def AddTimelinePath(builder, timelinePath):
    EventDefenseEnemySettingAddTimelinePath(builder, timelinePath)

def EventDefenseEnemySettingAddTimelineName(builder, timelineName):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timelineName), 0)

def AddTimelineName(builder, timelineName):
    EventDefenseEnemySettingAddTimelineName(builder, timelineName)

def EventDefenseEnemySettingAddModelType(builder, modelType):
    builder.PrependInt32Slot(5, modelType, 0)

def AddModelType(builder, modelType):
    EventDefenseEnemySettingAddModelType(builder, modelType)

def EventDefenseEnemySettingAddUseBossSlot(builder, useBossSlot):
    builder.PrependInt32Slot(6, useBossSlot, 0)

def AddUseBossSlot(builder, useBossSlot):
    EventDefenseEnemySettingAddUseBossSlot(builder, useBossSlot)

def EventDefenseEnemySettingAddMonsterType(builder, monsterType):
    builder.PrependInt32Slot(7, monsterType, 0)

def AddMonsterType(builder, monsterType):
    EventDefenseEnemySettingAddMonsterType(builder, monsterType)

def EventDefenseEnemySettingAddMonsterMoveType(builder, monsterMoveType):
    builder.PrependInt32Slot(8, monsterMoveType, 0)

def AddMonsterMoveType(builder, monsterMoveType):
    EventDefenseEnemySettingAddMonsterMoveType(builder, monsterMoveType)

def EventDefenseEnemySettingAddMaxCount(builder, maxCount):
    builder.PrependInt32Slot(9, maxCount, 0)

def AddMaxCount(builder, maxCount):
    EventDefenseEnemySettingAddMaxCount(builder, maxCount)

def EventDefenseEnemySettingAddScale(builder, scale):
    builder.PrependInt32Slot(10, scale, 0)

def AddScale(builder, scale):
    EventDefenseEnemySettingAddScale(builder, scale)

def EventDefenseEnemySettingAddMovedelay(builder, movedelay):
    builder.PrependInt32Slot(11, movedelay, 0)

def AddMovedelay(builder, movedelay):
    EventDefenseEnemySettingAddMovedelay(builder, movedelay)

def EventDefenseEnemySettingAddMovespeed(builder, movespeed):
    builder.PrependInt32Slot(12, movespeed, 0)

def AddMovespeed(builder, movespeed):
    EventDefenseEnemySettingAddMovespeed(builder, movespeed)

def EventDefenseEnemySettingAddMonsterAtk(builder, monsterAtk):
    builder.PrependInt32Slot(13, monsterAtk, 0)

def AddMonsterAtk(builder, monsterAtk):
    EventDefenseEnemySettingAddMonsterAtk(builder, monsterAtk)

def EventDefenseEnemySettingAddMonsterHp(builder, monsterHp):
    builder.PrependInt32Slot(14, monsterHp, 0)

def AddMonsterHp(builder, monsterHp):
    EventDefenseEnemySettingAddMonsterHp(builder, monsterHp)

def EventDefenseEnemySettingAddSpawnStartTime(builder, spawnStartTime):
    builder.PrependInt32Slot(15, spawnStartTime, 0)

def AddSpawnStartTime(builder, spawnStartTime):
    EventDefenseEnemySettingAddSpawnStartTime(builder, spawnStartTime)

def EventDefenseEnemySettingAddSpawnEndTime(builder, spawnEndTime):
    builder.PrependInt32Slot(16, spawnEndTime, 0)

def AddSpawnEndTime(builder, spawnEndTime):
    EventDefenseEnemySettingAddSpawnEndTime(builder, spawnEndTime)

def EventDefenseEnemySettingAddSpawnPerSec(builder, spawnPerSec):
    builder.PrependInt32Slot(17, spawnPerSec, 0)

def AddSpawnPerSec(builder, spawnPerSec):
    EventDefenseEnemySettingAddSpawnPerSec(builder, spawnPerSec)

def EventDefenseEnemySettingAddSpawnAmount(builder, spawnAmount):
    builder.PrependInt32Slot(18, spawnAmount, 0)

def AddSpawnAmount(builder, spawnAmount):
    EventDefenseEnemySettingAddSpawnAmount(builder, spawnAmount)

def EventDefenseEnemySettingAddScore(builder, score):
    builder.PrependInt32Slot(19, score, 0)

def AddScore(builder, score):
    EventDefenseEnemySettingAddScore(builder, score)

def EventDefenseEnemySettingAddExp(builder, exp):
    builder.PrependInt32Slot(20, exp, 0)

def AddExp(builder, exp):
    EventDefenseEnemySettingAddExp(builder, exp)

def EventDefenseEnemySettingAddItemDropProb(builder, itemDropProb):
    builder.PrependInt32Slot(21, itemDropProb, 0)

def AddItemDropProb(builder, itemDropProb):
    EventDefenseEnemySettingAddItemDropProb(builder, itemDropProb)

def EventDefenseEnemySettingAddItemDropList(builder, itemDropList):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(itemDropList), 0)

def AddItemDropList(builder, itemDropList):
    EventDefenseEnemySettingAddItemDropList(builder, itemDropList)

def EventDefenseEnemySettingEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDefenseEnemySettingEnd(builder)
