# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDefenseEnemySettingTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDefenseEnemySettingTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDefenseEnemySettingTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDefenseEnemySettingTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDefenseEnemySettingTable
    def EventDefenseEnemySettings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventDefenseEnemySetting import EventDefenseEnemySetting
            obj = EventDefenseEnemySetting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventDefenseEnemySettingTable
    def EventDefenseEnemySettingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventDefenseEnemySettingTable
    def EventDefenseEnemySettingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventDefenseEnemySettingTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventDefenseEnemySettingTableStart(builder)

def EventDefenseEnemySettingTableAddEventDefenseEnemySettings(builder, eventDefenseEnemySettings):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventDefenseEnemySettings), 0)

def AddEventDefenseEnemySettings(builder, eventDefenseEnemySettings):
    EventDefenseEnemySettingTableAddEventDefenseEnemySettings(builder, eventDefenseEnemySettings)

def EventDefenseEnemySettingTableStartEventDefenseEnemySettingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventDefenseEnemySettingsVector(builder, numElems):
    return EventDefenseEnemySettingTableStartEventDefenseEnemySettingsVector(builder, numElems)

def EventDefenseEnemySettingTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDefenseEnemySettingTableEnd(builder)
