# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDefenseAttackSettingTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDefenseAttackSettingTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDefenseAttackSettingTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDefenseAttackSettingTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDefenseAttackSettingTable
    def EventDefenseAttackSettings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventDefenseAttackSetting import EventDefenseAttackSetting
            obj = EventDefenseAttackSetting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventDefenseAttackSettingTable
    def EventDefenseAttackSettingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventDefenseAttackSettingTable
    def EventDefenseAttackSettingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventDefenseAttackSettingTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventDefenseAttackSettingTableStart(builder)

def EventDefenseAttackSettingTableAddEventDefenseAttackSettings(builder, eventDefenseAttackSettings):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventDefenseAttackSettings), 0)

def AddEventDefenseAttackSettings(builder, eventDefenseAttackSettings):
    EventDefenseAttackSettingTableAddEventDefenseAttackSettings(builder, eventDefenseAttackSettings)

def EventDefenseAttackSettingTableStartEventDefenseAttackSettingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventDefenseAttackSettingsVector(builder, numElems):
    return EventDefenseAttackSettingTableStartEventDefenseAttackSettingsVector(builder, numElems)

def EventDefenseAttackSettingTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDefenseAttackSettingTableEnd(builder)
