# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventBossRushUpgradeTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventBossRushUpgradeTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventBossRushUpgradeTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventBossRushUpgradeTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventBossRushUpgradeTable
    def EventBossRushUpgrades(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventBossRushUpgrade import EventBossRushUpgrade
            obj = EventBossRushUpgrade()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventBossRushUpgradeTable
    def EventBossRushUpgradesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventBossRushUpgradeTable
    def EventBossRushUpgradesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventBossRushUpgradeTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventBossRushUpgradeTableStart(builder)

def EventBossRushUpgradeTableAddEventBossRushUpgrades(builder, eventBossRushUpgrades):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventBossRushUpgrades), 0)

def AddEventBossRushUpgrades(builder, eventBossRushUpgrades):
    EventBossRushUpgradeTableAddEventBossRushUpgrades(builder, eventBossRushUpgrades)

def EventBossRushUpgradeTableStartEventBossRushUpgradesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventBossRushUpgradesVector(builder, numElems):
    return EventBossRushUpgradeTableStartEventBossRushUpgradesVector(builder, numElems)

def EventBossRushUpgradeTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventBossRushUpgradeTableEnd(builder)
