# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventDoubleStageBuff(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventDoubleStageBuff()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventDoubleStageBuff(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventDoubleStageBuff
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventDoubleStageBuff
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def EventGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def EventNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def BuffGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def BuffNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def BuffNameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventDoubleStageBuff
    def TooltipSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventDoubleStageBuffStart(builder):
    builder.StartObject(7)

def Start(builder):
    EventDoubleStageBuffStart(builder)

def EventDoubleStageBuffAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventDoubleStageBuffAddNo(builder, no)

def EventDoubleStageBuffAddEventGroup(builder, eventGroup):
    builder.PrependInt32Slot(1, eventGroup, 0)

def AddEventGroup(builder, eventGroup):
    EventDoubleStageBuffAddEventGroup(builder, eventGroup)

def EventDoubleStageBuffAddEventNumber(builder, eventNumber):
    builder.PrependInt32Slot(2, eventNumber, 0)

def AddEventNumber(builder, eventNumber):
    EventDoubleStageBuffAddEventNumber(builder, eventNumber)

def EventDoubleStageBuffAddBuffGroup(builder, buffGroup):
    builder.PrependInt32Slot(3, buffGroup, 0)

def AddBuffGroup(builder, buffGroup):
    EventDoubleStageBuffAddBuffGroup(builder, buffGroup)

def EventDoubleStageBuffAddBuffNo(builder, buffNo):
    builder.PrependInt32Slot(4, buffNo, 0)

def AddBuffNo(builder, buffNo):
    EventDoubleStageBuffAddBuffNo(builder, buffNo)

def EventDoubleStageBuffAddBuffNameSno(builder, buffNameSno):
    builder.PrependInt32Slot(5, buffNameSno, 0)

def AddBuffNameSno(builder, buffNameSno):
    EventDoubleStageBuffAddBuffNameSno(builder, buffNameSno)

def EventDoubleStageBuffAddTooltipSno(builder, tooltipSno):
    builder.PrependInt32Slot(6, tooltipSno, 0)

def AddTooltipSno(builder, tooltipSno):
    EventDoubleStageBuffAddTooltipSno(builder, tooltipSno)

def EventDoubleStageBuffEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventDoubleStageBuffEnd(builder)
