# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventRaidBuffTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventRaidBuffTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventRaidBuffTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventRaidBuffTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventRaidBuffTable
    def EventRaidBuffs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.EventRaidBuff import EventRaidBuff
            obj = EventRaidBuff()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventRaidBuffTable
    def EventRaidBuffsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventRaidBuffTable
    def EventRaidBuffsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EventRaidBuffTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    EventRaidBuffTableStart(builder)

def EventRaidBuffTableAddEventRaidBuffs(builder, eventRaidBuffs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventRaidBuffs), 0)

def AddEventRaidBuffs(builder, eventRaidBuffs):
    EventRaidBuffTableAddEventRaidBuffs(builder, eventRaidBuffs)

def EventRaidBuffTableStartEventRaidBuffsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEventRaidBuffsVector(builder, numElems):
    return EventRaidBuffTableStartEventRaidBuffsVector(builder, numElems)

def EventRaidBuffTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventRaidBuffTableEnd(builder)
