# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventRankRaidStepReward(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventRankRaidStepReward()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventRankRaidStepReward(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventRankRaidStepReward
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventRankRaidStepReward
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def EventGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def EventNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def GoalAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemNo1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemAmount1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemNo2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemAmount2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemNo3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemAmount3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemNo4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemAmount4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemNo5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventRankRaidStepReward
    def RewardItemAmount5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventRankRaidStepRewardStart(builder):
    builder.StartObject(15)

def Start(builder):
    EventRankRaidStepRewardStart(builder)

def EventRankRaidStepRewardAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    EventRankRaidStepRewardAddNo(builder, no)

def EventRankRaidStepRewardAddEventGroup(builder, eventGroup):
    builder.PrependInt32Slot(1, eventGroup, 0)

def AddEventGroup(builder, eventGroup):
    EventRankRaidStepRewardAddEventGroup(builder, eventGroup)

def EventRankRaidStepRewardAddEventNumber(builder, eventNumber):
    builder.PrependInt32Slot(2, eventNumber, 0)

def AddEventNumber(builder, eventNumber):
    EventRankRaidStepRewardAddEventNumber(builder, eventNumber)

def EventRankRaidStepRewardAddRewardType(builder, rewardType):
    builder.PrependInt32Slot(3, rewardType, 0)

def AddRewardType(builder, rewardType):
    EventRankRaidStepRewardAddRewardType(builder, rewardType)

def EventRankRaidStepRewardAddGoalAmount(builder, goalAmount):
    builder.PrependInt32Slot(4, goalAmount, 0)

def AddGoalAmount(builder, goalAmount):
    EventRankRaidStepRewardAddGoalAmount(builder, goalAmount)

def EventRankRaidStepRewardAddRewardItemNo1(builder, rewardItemNo1):
    builder.PrependInt32Slot(5, rewardItemNo1, 0)

def AddRewardItemNo1(builder, rewardItemNo1):
    EventRankRaidStepRewardAddRewardItemNo1(builder, rewardItemNo1)

def EventRankRaidStepRewardAddRewardItemAmount1(builder, rewardItemAmount1):
    builder.PrependInt32Slot(6, rewardItemAmount1, 0)

def AddRewardItemAmount1(builder, rewardItemAmount1):
    EventRankRaidStepRewardAddRewardItemAmount1(builder, rewardItemAmount1)

def EventRankRaidStepRewardAddRewardItemNo2(builder, rewardItemNo2):
    builder.PrependInt32Slot(7, rewardItemNo2, 0)

def AddRewardItemNo2(builder, rewardItemNo2):
    EventRankRaidStepRewardAddRewardItemNo2(builder, rewardItemNo2)

def EventRankRaidStepRewardAddRewardItemAmount2(builder, rewardItemAmount2):
    builder.PrependInt32Slot(8, rewardItemAmount2, 0)

def AddRewardItemAmount2(builder, rewardItemAmount2):
    EventRankRaidStepRewardAddRewardItemAmount2(builder, rewardItemAmount2)

def EventRankRaidStepRewardAddRewardItemNo3(builder, rewardItemNo3):
    builder.PrependInt32Slot(9, rewardItemNo3, 0)

def AddRewardItemNo3(builder, rewardItemNo3):
    EventRankRaidStepRewardAddRewardItemNo3(builder, rewardItemNo3)

def EventRankRaidStepRewardAddRewardItemAmount3(builder, rewardItemAmount3):
    builder.PrependInt32Slot(10, rewardItemAmount3, 0)

def AddRewardItemAmount3(builder, rewardItemAmount3):
    EventRankRaidStepRewardAddRewardItemAmount3(builder, rewardItemAmount3)

def EventRankRaidStepRewardAddRewardItemNo4(builder, rewardItemNo4):
    builder.PrependInt32Slot(11, rewardItemNo4, 0)

def AddRewardItemNo4(builder, rewardItemNo4):
    EventRankRaidStepRewardAddRewardItemNo4(builder, rewardItemNo4)

def EventRankRaidStepRewardAddRewardItemAmount4(builder, rewardItemAmount4):
    builder.PrependInt32Slot(12, rewardItemAmount4, 0)

def AddRewardItemAmount4(builder, rewardItemAmount4):
    EventRankRaidStepRewardAddRewardItemAmount4(builder, rewardItemAmount4)

def EventRankRaidStepRewardAddRewardItemNo5(builder, rewardItemNo5):
    builder.PrependInt32Slot(13, rewardItemNo5, 0)

def AddRewardItemNo5(builder, rewardItemNo5):
    EventRankRaidStepRewardAddRewardItemNo5(builder, rewardItemNo5)

def EventRankRaidStepRewardAddRewardItemAmount5(builder, rewardItemAmount5):
    builder.PrependInt32Slot(14, rewardItemAmount5, 0)

def AddRewardItemAmount5(builder, rewardItemAmount5):
    EventRankRaidStepRewardAddRewardItemAmount5(builder, rewardItemAmount5)

def EventRankRaidStepRewardEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventRankRaidStepRewardEnd(builder)
