# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaMileageRewardTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaMileageRewardTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGachaMileageRewardTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GachaMileageRewardTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaMileageRewardTable
    def GachaMileageRewards(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.GachaMileageReward import GachaMileageReward
            obj = GachaMileageReward()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GachaMileageRewardTable
    def GachaMileageRewardsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GachaMileageRewardTable
    def GachaMileageRewardsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GachaMileageRewardTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    GachaMileageRewardTableStart(builder)

def GachaMileageRewardTableAddGachaMileageRewards(builder, gachaMileageRewards):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gachaMileageRewards), 0)

def AddGachaMileageRewards(builder, gachaMileageRewards):
    GachaMileageRewardTableAddGachaMileageRewards(builder, gachaMileageRewards)

def GachaMileageRewardTableStartGachaMileageRewardsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGachaMileageRewardsVector(builder, numElems):
    return GachaMileageRewardTableStartGachaMileageRewardsVector(builder, numElems)

def GachaMileageRewardTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return GachaMileageRewardTableEnd(builder)
