# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGachaTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GachaTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaTable
    def Gachas(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Gacha import Gacha
            obj = Gacha()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GachaTable
    def GachasLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GachaTable
    def GachasIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GachaTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    GachaTableStart(builder)

def GachaTableAddGachas(builder, gachas):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gachas), 0)

def AddGachas(builder, gachas):
    GachaTableAddGachas(builder, gachas)

def GachaTableStartGachasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGachasVector(builder, numElems):
    return GachaTableStartGachasVector(builder, numElems)

def GachaTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return GachaTableEnd(builder)
