# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaMileageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaMileageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGachaMileageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GachaMileageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaMileageTable
    def GachaMileages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.GachaMileage import GachaMileage
            obj = GachaMileage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GachaMileageTable
    def GachaMileagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GachaMileageTable
    def GachaMileagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GachaMileageTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    GachaMileageTableStart(builder)

def GachaMileageTableAddGachaMileages(builder, gachaMileages):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gachaMileages), 0)

def AddGachaMileages(builder, gachaMileages):
    GachaMileageTableAddGachaMileages(builder, gachaMileages)

def GachaMileageTableStartGachaMileagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGachaMileagesVector(builder, numElems):
    return GachaMileageTableStartGachaMileagesVector(builder, numElems)

def GachaMileageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return GachaMileageTableEnd(builder)
