# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GuideQuestListTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GuideQuestListTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGuideQuestListTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GuideQuestListTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GuideQuestListTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.GuideQuestList import GuideQuestList
            obj = GuideQuestList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GuideQuestListTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GuideQuestListTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GuideQuestListTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    GuideQuestListTableStart(builder)

def GuideQuestListTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    GuideQuestListTableAddJson(builder, json)

def GuideQuestListTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return GuideQuestListTableStartJsonVector(builder, numElems)

def GuideQuestListTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return GuideQuestListTableEnd(builder)
