# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GuideQuestTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GuideQuestTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGuideQuestTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GuideQuestTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GuideQuestTable
    def GuideQuests(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.GuideQuest import GuideQuest
            obj = GuideQuest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GuideQuestTable
    def GuideQuestsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GuideQuestTable
    def GuideQuestsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GuideQuestTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    GuideQuestTableStart(builder)

def GuideQuestTableAddGuideQuests(builder, guideQuests):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(guideQuests), 0)

def AddGuideQuests(builder, guideQuests):
    GuideQuestTableAddGuideQuests(builder, guideQuests)

def GuideQuestTableStartGuideQuestsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGuideQuestsVector(builder, numElems):
    return GuideQuestTableStartGuideQuestsVector(builder, numElems)

def GuideQuestTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return GuideQuestTableEnd(builder)
