# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HelpGuideCategoryTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HelpGuideCategoryTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHelpGuideCategoryTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HelpGuideCategoryTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HelpGuideCategoryTable
    def HelpGuideCategorys(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.HelpGuideCategory import HelpGuideCategory
            obj = HelpGuideCategory()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HelpGuideCategoryTable
    def HelpGuideCategorysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HelpGuideCategoryTable
    def HelpGuideCategorysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HelpGuideCategoryTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    HelpGuideCategoryTableStart(builder)

def HelpGuideCategoryTableAddHelpGuideCategorys(builder, helpGuideCategorys):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(helpGuideCategorys), 0)

def AddHelpGuideCategorys(builder, helpGuideCategorys):
    HelpGuideCategoryTableAddHelpGuideCategorys(builder, helpGuideCategorys)

def HelpGuideCategoryTableStartHelpGuideCategorysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartHelpGuideCategorysVector(builder, numElems):
    return HelpGuideCategoryTableStartHelpGuideCategorysVector(builder, numElems)

def HelpGuideCategoryTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return HelpGuideCategoryTableEnd(builder)
