# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeroLoveBuffTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeroLoveBuffTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeroLoveBuffTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeroLoveBuffTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeroLoveBuffTable
    def HeroLoveBuffs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.HeroLoveBuff import HeroLoveBuff
            obj = HeroLoveBuff()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HeroLoveBuffTable
    def HeroLoveBuffsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HeroLoveBuffTable
    def HeroLoveBuffsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HeroLoveBuffTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    HeroLoveBuffTableStart(builder)

def HeroLoveBuffTableAddHeroLoveBuffs(builder, heroLoveBuffs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(heroLoveBuffs), 0)

def AddHeroLoveBuffs(builder, heroLoveBuffs):
    HeroLoveBuffTableAddHeroLoveBuffs(builder, heroLoveBuffs)

def HeroLoveBuffTableStartHeroLoveBuffsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartHeroLoveBuffsVector(builder, numElems):
    return HeroLoveBuffTableStartHeroLoveBuffsVector(builder, numElems)

def HeroLoveBuffTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeroLoveBuffTableEnd(builder)
