# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeroWishSchedule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeroWishSchedule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeroWishSchedule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeroWishSchedule
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeroWishSchedule
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishSchedule
    def HeroCheck(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishSchedule
    def WishlistTier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishSchedule
    def ViewType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishSchedule
    def ServerCheck(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishSchedule
    def OpenDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HeroWishScheduleStart(builder):
    builder.StartObject(6)

def Start(builder):
    HeroWishScheduleStart(builder)

def HeroWishScheduleAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    HeroWishScheduleAddNo(builder, no)

def HeroWishScheduleAddHeroCheck(builder, heroCheck):
    builder.PrependInt32Slot(1, heroCheck, 0)

def AddHeroCheck(builder, heroCheck):
    HeroWishScheduleAddHeroCheck(builder, heroCheck)

def HeroWishScheduleAddWishlistTier(builder, wishlistTier):
    builder.PrependInt32Slot(2, wishlistTier, 0)

def AddWishlistTier(builder, wishlistTier):
    HeroWishScheduleAddWishlistTier(builder, wishlistTier)

def HeroWishScheduleAddViewType(builder, viewType):
    builder.PrependInt32Slot(3, viewType, 0)

def AddViewType(builder, viewType):
    HeroWishScheduleAddViewType(builder, viewType)

def HeroWishScheduleAddServerCheck(builder, serverCheck):
    builder.PrependInt32Slot(4, serverCheck, 0)

def AddServerCheck(builder, serverCheck):
    HeroWishScheduleAddServerCheck(builder, serverCheck)

def HeroWishScheduleAddOpenDate(builder, openDate):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(openDate), 0)

def AddOpenDate(builder, openDate):
    HeroWishScheduleAddOpenDate(builder, openDate)

def HeroWishScheduleEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeroWishScheduleEnd(builder)
