# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeroRental(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeroRental()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeroRental(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeroRental
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeroRental
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def GradeEpicSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def GradeRareSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def GradeEquipSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def ItemLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def SignatureLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroRental
    def SignatureSkillLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HeroRentalStart(builder):
    builder.StartObject(7)

def Start(builder):
    HeroRentalStart(builder)

def HeroRentalAddLevel(builder, level):
    builder.PrependInt32Slot(0, level, 0)

def AddLevel(builder, level):
    HeroRentalAddLevel(builder, level)

def HeroRentalAddGradeEpicSno(builder, gradeEpicSno):
    builder.PrependInt32Slot(1, gradeEpicSno, 0)

def AddGradeEpicSno(builder, gradeEpicSno):
    HeroRentalAddGradeEpicSno(builder, gradeEpicSno)

def HeroRentalAddGradeRareSno(builder, gradeRareSno):
    builder.PrependInt32Slot(2, gradeRareSno, 0)

def AddGradeRareSno(builder, gradeRareSno):
    HeroRentalAddGradeRareSno(builder, gradeRareSno)

def HeroRentalAddGradeEquipSno(builder, gradeEquipSno):
    builder.PrependInt32Slot(3, gradeEquipSno, 0)

def AddGradeEquipSno(builder, gradeEquipSno):
    HeroRentalAddGradeEquipSno(builder, gradeEquipSno)

def HeroRentalAddItemLevel(builder, itemLevel):
    builder.PrependInt32Slot(4, itemLevel, 0)

def AddItemLevel(builder, itemLevel):
    HeroRentalAddItemLevel(builder, itemLevel)

def HeroRentalAddSignatureLevel(builder, signatureLevel):
    builder.PrependInt32Slot(5, signatureLevel, 0)

def AddSignatureLevel(builder, signatureLevel):
    HeroRentalAddSignatureLevel(builder, signatureLevel)

def HeroRentalAddSignatureSkillLevel(builder, signatureSkillLevel):
    builder.PrependInt32Slot(6, signatureSkillLevel, 0)

def AddSignatureSkillLevel(builder, signatureSkillLevel):
    HeroRentalAddSignatureSkillLevel(builder, signatureSkillLevel)

def HeroRentalEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeroRentalEnd(builder)
