# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeroWishGachaSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeroWishGachaSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeroWishGachaSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeroWishGachaSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeroWishGachaSlot
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishGachaSlot
    def WishslotGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishGachaSlot
    def WishlistTier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishGachaSlot
    def SlotCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeroWishGachaSlot
    def SlotType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HeroWishGachaSlotStart(builder):
    builder.StartObject(5)

def Start(builder):
    HeroWishGachaSlotStart(builder)

def HeroWishGachaSlotAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    HeroWishGachaSlotAddNo(builder, no)

def HeroWishGachaSlotAddWishslotGroup(builder, wishslotGroup):
    builder.PrependInt32Slot(1, wishslotGroup, 0)

def AddWishslotGroup(builder, wishslotGroup):
    HeroWishGachaSlotAddWishslotGroup(builder, wishslotGroup)

def HeroWishGachaSlotAddWishlistTier(builder, wishlistTier):
    builder.PrependInt32Slot(2, wishlistTier, 0)

def AddWishlistTier(builder, wishlistTier):
    HeroWishGachaSlotAddWishlistTier(builder, wishlistTier)

def HeroWishGachaSlotAddSlotCount(builder, slotCount):
    builder.PrependInt32Slot(3, slotCount, 0)

def AddSlotCount(builder, slotCount):
    HeroWishGachaSlotAddSlotCount(builder, slotCount)

def HeroWishGachaSlotAddSlotType(builder, slotType):
    builder.PrependInt32Slot(4, slotType, 0)

def AddSlotType(builder, slotType):
    HeroWishGachaSlotAddSlotType(builder, slotType)

def HeroWishGachaSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeroWishGachaSlotEnd(builder)
