# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IllustTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IllustTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIllustTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IllustTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IllustTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Illust import Illust
            obj = Illust()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IllustTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IllustTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def IllustTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    IllustTableStart(builder)

def IllustTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    IllustTableAddJson(builder, json)

def IllustTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return IllustTableStartJsonVector(builder, numElems)

def IllustTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return IllustTableEnd(builder)
