# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Immune(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Immune()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImmune(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Immune
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Immune
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect6(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect7(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect8(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect9(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Immune
    def BuffEffect10(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ImmuneStart(builder):
    builder.StartObject(11)

def Start(builder):
    ImmuneStart(builder)

def ImmuneAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    ImmuneAddNo(builder, no)

def ImmuneAddBuffEffect1(builder, buffEffect1):
    builder.PrependInt32Slot(1, buffEffect1, 0)

def AddBuffEffect1(builder, buffEffect1):
    ImmuneAddBuffEffect1(builder, buffEffect1)

def ImmuneAddBuffEffect2(builder, buffEffect2):
    builder.PrependInt32Slot(2, buffEffect2, 0)

def AddBuffEffect2(builder, buffEffect2):
    ImmuneAddBuffEffect2(builder, buffEffect2)

def ImmuneAddBuffEffect3(builder, buffEffect3):
    builder.PrependInt32Slot(3, buffEffect3, 0)

def AddBuffEffect3(builder, buffEffect3):
    ImmuneAddBuffEffect3(builder, buffEffect3)

def ImmuneAddBuffEffect4(builder, buffEffect4):
    builder.PrependInt32Slot(4, buffEffect4, 0)

def AddBuffEffect4(builder, buffEffect4):
    ImmuneAddBuffEffect4(builder, buffEffect4)

def ImmuneAddBuffEffect5(builder, buffEffect5):
    builder.PrependInt32Slot(5, buffEffect5, 0)

def AddBuffEffect5(builder, buffEffect5):
    ImmuneAddBuffEffect5(builder, buffEffect5)

def ImmuneAddBuffEffect6(builder, buffEffect6):
    builder.PrependInt32Slot(6, buffEffect6, 0)

def AddBuffEffect6(builder, buffEffect6):
    ImmuneAddBuffEffect6(builder, buffEffect6)

def ImmuneAddBuffEffect7(builder, buffEffect7):
    builder.PrependInt32Slot(7, buffEffect7, 0)

def AddBuffEffect7(builder, buffEffect7):
    ImmuneAddBuffEffect7(builder, buffEffect7)

def ImmuneAddBuffEffect8(builder, buffEffect8):
    builder.PrependInt32Slot(8, buffEffect8, 0)

def AddBuffEffect8(builder, buffEffect8):
    ImmuneAddBuffEffect8(builder, buffEffect8)

def ImmuneAddBuffEffect9(builder, buffEffect9):
    builder.PrependInt32Slot(9, buffEffect9, 0)

def AddBuffEffect9(builder, buffEffect9):
    ImmuneAddBuffEffect9(builder, buffEffect9)

def ImmuneAddBuffEffect10(builder, buffEffect10):
    builder.PrependInt32Slot(10, buffEffect10, 0)

def AddBuffEffect10(builder, buffEffect10):
    ImmuneAddBuffEffect10(builder, buffEffect10)

def ImmuneEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImmuneEnd(builder)
