# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImmuneBuffTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImmuneBuffTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImmuneBuffTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImmuneBuffTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImmuneBuffTable
    def ImmuneBuffs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.ImmuneBuff import ImmuneBuff
            obj = ImmuneBuff()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImmuneBuffTable
    def ImmuneBuffsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImmuneBuffTable
    def ImmuneBuffsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ImmuneBuffTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    ImmuneBuffTableStart(builder)

def ImmuneBuffTableAddImmuneBuffs(builder, immuneBuffs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(immuneBuffs), 0)

def AddImmuneBuffs(builder, immuneBuffs):
    ImmuneBuffTableAddImmuneBuffs(builder, immuneBuffs)

def ImmuneBuffTableStartImmuneBuffsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartImmuneBuffsVector(builder, numElems):
    return ImmuneBuffTableStartImmuneBuffsVector(builder, numElems)

def ImmuneBuffTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImmuneBuffTableEnd(builder)
