# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ItemDropGroupTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ItemDropGroupTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItemDropGroupTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ItemDropGroupTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ItemDropGroupTable
    def ItemDropGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.ItemDropGroup import ItemDropGroup
            obj = ItemDropGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ItemDropGroupTable
    def ItemDropGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ItemDropGroupTable
    def ItemDropGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ItemDropGroupTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    ItemDropGroupTableStart(builder)

def ItemDropGroupTableAddItemDropGroups(builder, itemDropGroups):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(itemDropGroups), 0)

def AddItemDropGroups(builder, itemDropGroups):
    ItemDropGroupTableAddItemDropGroups(builder, itemDropGroups)

def ItemDropGroupTableStartItemDropGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemDropGroupsVector(builder, numElems):
    return ItemDropGroupTableStartItemDropGroupsVector(builder, numElems)

def ItemDropGroupTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ItemDropGroupTableEnd(builder)
