# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ItemStat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ItemStat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItemStat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ItemStat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ItemStat
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def Exp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def SumExp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def Attack(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def Defence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def MaxHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def CriticalRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def CriticalPower(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def Hit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def Dodge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def PhysicalResist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def MagicResist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def LifeLeech(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def AttackSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def BattlePower(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ItemStat
    def AttackRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def DefenceRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def HpRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ItemStat
    def BattlePowerPer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ItemStatStart(builder):
    builder.StartObject(21)

def Start(builder):
    ItemStatStart(builder)

def ItemStatAddIndex(builder, index):
    builder.PrependInt32Slot(0, index, 0)

def AddIndex(builder, index):
    ItemStatAddIndex(builder, index)

def ItemStatAddNo(builder, no):
    builder.PrependInt32Slot(1, no, 0)

def AddNo(builder, no):
    ItemStatAddNo(builder, no)

def ItemStatAddLevel(builder, level):
    builder.PrependInt32Slot(2, level, 0)

def AddLevel(builder, level):
    ItemStatAddLevel(builder, level)

def ItemStatAddExp(builder, exp):
    builder.PrependInt32Slot(3, exp, 0)

def AddExp(builder, exp):
    ItemStatAddExp(builder, exp)

def ItemStatAddSumExp(builder, sumExp):
    builder.PrependInt32Slot(4, sumExp, 0)

def AddSumExp(builder, sumExp):
    ItemStatAddSumExp(builder, sumExp)

def ItemStatAddAttack(builder, attack):
    builder.PrependInt32Slot(5, attack, 0)

def AddAttack(builder, attack):
    ItemStatAddAttack(builder, attack)

def ItemStatAddDefence(builder, defence):
    builder.PrependInt32Slot(6, defence, 0)

def AddDefence(builder, defence):
    ItemStatAddDefence(builder, defence)

def ItemStatAddMaxHp(builder, maxHp):
    builder.PrependInt32Slot(7, maxHp, 0)

def AddMaxHp(builder, maxHp):
    ItemStatAddMaxHp(builder, maxHp)

def ItemStatAddCriticalRate(builder, criticalRate):
    builder.PrependFloat32Slot(8, criticalRate, 0.0)

def AddCriticalRate(builder, criticalRate):
    ItemStatAddCriticalRate(builder, criticalRate)

def ItemStatAddCriticalPower(builder, criticalPower):
    builder.PrependFloat32Slot(9, criticalPower, 0.0)

def AddCriticalPower(builder, criticalPower):
    ItemStatAddCriticalPower(builder, criticalPower)

def ItemStatAddHit(builder, hit):
    builder.PrependInt32Slot(10, hit, 0)

def AddHit(builder, hit):
    ItemStatAddHit(builder, hit)

def ItemStatAddDodge(builder, dodge):
    builder.PrependInt32Slot(11, dodge, 0)

def AddDodge(builder, dodge):
    ItemStatAddDodge(builder, dodge)

def ItemStatAddPhysicalResist(builder, physicalResist):
    builder.PrependFloat32Slot(12, physicalResist, 0.0)

def AddPhysicalResist(builder, physicalResist):
    ItemStatAddPhysicalResist(builder, physicalResist)

def ItemStatAddMagicResist(builder, magicResist):
    builder.PrependFloat32Slot(13, magicResist, 0.0)

def AddMagicResist(builder, magicResist):
    ItemStatAddMagicResist(builder, magicResist)

def ItemStatAddLifeLeech(builder, lifeLeech):
    builder.PrependFloat32Slot(14, lifeLeech, 0.0)

def AddLifeLeech(builder, lifeLeech):
    ItemStatAddLifeLeech(builder, lifeLeech)

def ItemStatAddAttackSpeed(builder, attackSpeed):
    builder.PrependFloat32Slot(15, attackSpeed, 0.0)

def AddAttackSpeed(builder, attackSpeed):
    ItemStatAddAttackSpeed(builder, attackSpeed)

def ItemStatAddBattlePower(builder, battlePower):
    builder.PrependInt32Slot(16, battlePower, 0)

def AddBattlePower(builder, battlePower):
    ItemStatAddBattlePower(builder, battlePower)

def ItemStatAddAttackRate(builder, attackRate):
    builder.PrependFloat32Slot(17, attackRate, 0.0)

def AddAttackRate(builder, attackRate):
    ItemStatAddAttackRate(builder, attackRate)

def ItemStatAddDefenceRate(builder, defenceRate):
    builder.PrependFloat32Slot(18, defenceRate, 0.0)

def AddDefenceRate(builder, defenceRate):
    ItemStatAddDefenceRate(builder, defenceRate)

def ItemStatAddHpRate(builder, hpRate):
    builder.PrependFloat32Slot(19, hpRate, 0.0)

def AddHpRate(builder, hpRate):
    ItemStatAddHpRate(builder, hpRate)

def ItemStatAddBattlePowerPer(builder, battlePowerPer):
    builder.PrependFloat32Slot(20, battlePowerPer, 0.0)

def AddBattlePowerPer(builder, battlePowerPer):
    ItemStatAddBattlePowerPer(builder, battlePowerPer)

def ItemStatEnd(builder):
    return builder.EndObject()

def End(builder):
    return ItemStatEnd(builder)
