# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ItemSetEffectTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ItemSetEffectTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItemSetEffectTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ItemSetEffectTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ItemSetEffectTable
    def ItemSetEffects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.ItemSetEffect import ItemSetEffect
            obj = ItemSetEffect()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ItemSetEffectTable
    def ItemSetEffectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ItemSetEffectTable
    def ItemSetEffectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ItemSetEffectTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    ItemSetEffectTableStart(builder)

def ItemSetEffectTableAddItemSetEffects(builder, itemSetEffects):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(itemSetEffects), 0)

def AddItemSetEffects(builder, itemSetEffects):
    ItemSetEffectTableAddItemSetEffects(builder, itemSetEffects)

def ItemSetEffectTableStartItemSetEffectsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemSetEffectsVector(builder, numElems):
    return ItemSetEffectTableStartItemSetEffectsVector(builder, numElems)

def ItemSetEffectTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ItemSetEffectTableEnd(builder)
