# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LobbyBGM(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LobbyBGM()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLobbyBGM(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LobbyBGM
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LobbyBGM
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def Order(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def TypeValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def Grade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def TitleSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def ArrangeSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def ItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LobbyBGM
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LobbyBGM
    def BgmName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LobbyBGMStart(builder):
    builder.StartObject(10)

def Start(builder):
    LobbyBGMStart(builder)

def LobbyBGMAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    LobbyBGMAddNo(builder, no)

def LobbyBGMAddOrder(builder, order):
    builder.PrependInt32Slot(1, order, 0)

def AddOrder(builder, order):
    LobbyBGMAddOrder(builder, order)

def LobbyBGMAddType(builder, type):
    builder.PrependInt32Slot(2, type, 0)

def AddType(builder, type):
    LobbyBGMAddType(builder, type)

def LobbyBGMAddTypeValue(builder, typeValue):
    builder.PrependInt32Slot(3, typeValue, 0)

def AddTypeValue(builder, typeValue):
    LobbyBGMAddTypeValue(builder, typeValue)

def LobbyBGMAddGrade(builder, grade):
    builder.PrependInt32Slot(4, grade, 0)

def AddGrade(builder, grade):
    LobbyBGMAddGrade(builder, grade)

def LobbyBGMAddTitleSno(builder, titleSno):
    builder.PrependInt32Slot(5, titleSno, 0)

def AddTitleSno(builder, titleSno):
    LobbyBGMAddTitleSno(builder, titleSno)

def LobbyBGMAddArrangeSno(builder, arrangeSno):
    builder.PrependInt32Slot(6, arrangeSno, 0)

def AddArrangeSno(builder, arrangeSno):
    LobbyBGMAddArrangeSno(builder, arrangeSno)

def LobbyBGMAddItemNo(builder, itemNo):
    builder.PrependInt32Slot(7, itemNo, 0)

def AddItemNo(builder, itemNo):
    LobbyBGMAddItemNo(builder, itemNo)

def LobbyBGMAddImagePath(builder, imagePath):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(imagePath), 0)

def AddImagePath(builder, imagePath):
    LobbyBGMAddImagePath(builder, imagePath)

def LobbyBGMAddBgmName(builder, bgmName):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(bgmName), 0)

def AddBgmName(builder, bgmName):
    LobbyBGMAddBgmName(builder, bgmName)

def LobbyBGMEnd(builder):
    return builder.EndObject()

def End(builder):
    return LobbyBGMEnd(builder)
