# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LobbyBGMTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LobbyBGMTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLobbyBGMTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LobbyBGMTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LobbyBGMTable
    def LobbyBgMs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.LobbyBGM import LobbyBGM
            obj = LobbyBGM()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LobbyBGMTable
    def LobbyBgMsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LobbyBGMTable
    def LobbyBgMsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def LobbyBGMTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    LobbyBGMTableStart(builder)

def LobbyBGMTableAddLobbyBgMs(builder, lobbyBgMs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lobbyBgMs), 0)

def AddLobbyBgMs(builder, lobbyBgMs):
    LobbyBGMTableAddLobbyBgMs(builder, lobbyBgMs)

def LobbyBGMTableStartLobbyBgMsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLobbyBgMsVector(builder, numElems):
    return LobbyBGMTableStartLobbyBgMsVector(builder, numElems)

def LobbyBGMTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return LobbyBGMTableEnd(builder)
