# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProfileObjectsListTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProfileObjectsListTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProfileObjectsListTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProfileObjectsListTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProfileObjectsListTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.ProfileObjectsList import ProfileObjectsList
            obj = ProfileObjectsList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProfileObjectsListTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProfileObjectsListTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ProfileObjectsListTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    ProfileObjectsListTableStart(builder)

def ProfileObjectsListTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    ProfileObjectsListTableAddJson(builder, json)

def ProfileObjectsListTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return ProfileObjectsListTableStartJsonVector(builder, numElems)

def ProfileObjectsListTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProfileObjectsListTableEnd(builder)
