# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RaceCounterTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RaceCounterTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRaceCounterTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RaceCounterTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RaceCounterTable
    def RaceCounters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.RaceCounter import RaceCounter
            obj = RaceCounter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RaceCounterTable
    def RaceCountersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaceCounterTable
    def RaceCountersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def RaceCounterTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    RaceCounterTableStart(builder)

def RaceCounterTableAddRaceCounters(builder, raceCounters):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(raceCounters), 0)

def AddRaceCounters(builder, raceCounters):
    RaceCounterTableAddRaceCounters(builder, raceCounters)

def RaceCounterTableStartRaceCountersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRaceCountersVector(builder, numElems):
    return RaceCounterTableStartRaceCountersVector(builder, numElems)

def RaceCounterTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return RaceCounterTableEnd(builder)
