# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RentalTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RentalTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRentalTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RentalTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RentalTable
    def Rentals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Rental import Rental
            obj = Rental()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RentalTable
    def RentalsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RentalTable
    def RentalsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def RentalTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    RentalTableStart(builder)

def RentalTableAddRentals(builder, rentals):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rentals), 0)

def AddRentals(builder, rentals):
    RentalTableAddRentals(builder, rentals)

def RentalTableStartRentalsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRentalsVector(builder, numElems):
    return RentalTableStartRentalsVector(builder, numElems)

def RentalTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return RentalTableEnd(builder)
