# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopRandom(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopRandom()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopRandom(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopRandom
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopRandom
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def ShopNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def PayItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def PayItemAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def RepeatDrawBox(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopRandom
    def BgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopRandom
    def ShopImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopRandom
    def UseTitle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def ShopNameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def EventShopHero(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def ModelViewerDisplay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def ModelOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopRandom
    def TipSno1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def TipSno2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def TipSno3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip2Sno1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip2Sno2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip2Sno3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip3Sno1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip3Sno2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandom
    def Tip3Sno3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ShopRandomStart(builder):
    builder.StartObject(21)

def Start(builder):
    ShopRandomStart(builder)

def ShopRandomAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    ShopRandomAddNo(builder, no)

def ShopRandomAddShopNo(builder, shopNo):
    builder.PrependInt32Slot(1, shopNo, 0)

def AddShopNo(builder, shopNo):
    ShopRandomAddShopNo(builder, shopNo)

def ShopRandomAddPayItemNo(builder, payItemNo):
    builder.PrependInt32Slot(2, payItemNo, 0)

def AddPayItemNo(builder, payItemNo):
    ShopRandomAddPayItemNo(builder, payItemNo)

def ShopRandomAddPayItemAmount(builder, payItemAmount):
    builder.PrependInt32Slot(3, payItemAmount, 0)

def AddPayItemAmount(builder, payItemAmount):
    ShopRandomAddPayItemAmount(builder, payItemAmount)

def ShopRandomAddRepeatDrawBox(builder, repeatDrawBox):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(repeatDrawBox), 0)

def AddRepeatDrawBox(builder, repeatDrawBox):
    ShopRandomAddRepeatDrawBox(builder, repeatDrawBox)

def ShopRandomAddBgPath(builder, bgPath):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bgPath), 0)

def AddBgPath(builder, bgPath):
    ShopRandomAddBgPath(builder, bgPath)

def ShopRandomAddShopImagePath(builder, shopImagePath):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(shopImagePath), 0)

def AddShopImagePath(builder, shopImagePath):
    ShopRandomAddShopImagePath(builder, shopImagePath)

def ShopRandomAddUseTitle(builder, useTitle):
    builder.PrependInt32Slot(7, useTitle, 0)

def AddUseTitle(builder, useTitle):
    ShopRandomAddUseTitle(builder, useTitle)

def ShopRandomAddShopNameSno(builder, shopNameSno):
    builder.PrependInt32Slot(8, shopNameSno, 0)

def AddShopNameSno(builder, shopNameSno):
    ShopRandomAddShopNameSno(builder, shopNameSno)

def ShopRandomAddEventShopHero(builder, eventShopHero):
    builder.PrependInt32Slot(9, eventShopHero, 0)

def AddEventShopHero(builder, eventShopHero):
    ShopRandomAddEventShopHero(builder, eventShopHero)

def ShopRandomAddModelViewerDisplay(builder, modelViewerDisplay):
    builder.PrependInt32Slot(10, modelViewerDisplay, 0)

def AddModelViewerDisplay(builder, modelViewerDisplay):
    ShopRandomAddModelViewerDisplay(builder, modelViewerDisplay)

def ShopRandomAddModelOffset(builder, modelOffset):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(modelOffset), 0)

def AddModelOffset(builder, modelOffset):
    ShopRandomAddModelOffset(builder, modelOffset)

def ShopRandomAddTipSno1(builder, tipSno1):
    builder.PrependInt32Slot(12, tipSno1, 0)

def AddTipSno1(builder, tipSno1):
    ShopRandomAddTipSno1(builder, tipSno1)

def ShopRandomAddTipSno2(builder, tipSno2):
    builder.PrependInt32Slot(13, tipSno2, 0)

def AddTipSno2(builder, tipSno2):
    ShopRandomAddTipSno2(builder, tipSno2)

def ShopRandomAddTipSno3(builder, tipSno3):
    builder.PrependInt32Slot(14, tipSno3, 0)

def AddTipSno3(builder, tipSno3):
    ShopRandomAddTipSno3(builder, tipSno3)

def ShopRandomAddTip2Sno1(builder, tip2Sno1):
    builder.PrependInt32Slot(15, tip2Sno1, 0)

def AddTip2Sno1(builder, tip2Sno1):
    ShopRandomAddTip2Sno1(builder, tip2Sno1)

def ShopRandomAddTip2Sno2(builder, tip2Sno2):
    builder.PrependInt32Slot(16, tip2Sno2, 0)

def AddTip2Sno2(builder, tip2Sno2):
    ShopRandomAddTip2Sno2(builder, tip2Sno2)

def ShopRandomAddTip2Sno3(builder, tip2Sno3):
    builder.PrependInt32Slot(17, tip2Sno3, 0)

def AddTip2Sno3(builder, tip2Sno3):
    ShopRandomAddTip2Sno3(builder, tip2Sno3)

def ShopRandomAddTip3Sno1(builder, tip3Sno1):
    builder.PrependInt32Slot(18, tip3Sno1, 0)

def AddTip3Sno1(builder, tip3Sno1):
    ShopRandomAddTip3Sno1(builder, tip3Sno1)

def ShopRandomAddTip3Sno2(builder, tip3Sno2):
    builder.PrependInt32Slot(19, tip3Sno2, 0)

def AddTip3Sno2(builder, tip3Sno2):
    ShopRandomAddTip3Sno2(builder, tip3Sno2)

def ShopRandomAddTip3Sno3(builder, tip3Sno3):
    builder.PrependInt32Slot(20, tip3Sno3, 0)

def AddTip3Sno3(builder, tip3Sno3):
    ShopRandomAddTip3Sno3(builder, tip3Sno3)

def ShopRandomEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShopRandomEnd(builder)
