# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopRandomItems(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopRandomItems()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopRandomItems(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopRandomItems
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopRandomItems
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def ShopNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def DrawBox(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def ItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def ItemAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def DrawLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def ItemType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopRandomItems
    def DrawWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ShopRandomItemsStart(builder):
    builder.StartObject(8)

def Start(builder):
    ShopRandomItemsStart(builder)

def ShopRandomItemsAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    ShopRandomItemsAddNo(builder, no)

def ShopRandomItemsAddShopNo(builder, shopNo):
    builder.PrependInt32Slot(1, shopNo, 0)

def AddShopNo(builder, shopNo):
    ShopRandomItemsAddShopNo(builder, shopNo)

def ShopRandomItemsAddDrawBox(builder, drawBox):
    builder.PrependInt32Slot(2, drawBox, 0)

def AddDrawBox(builder, drawBox):
    ShopRandomItemsAddDrawBox(builder, drawBox)

def ShopRandomItemsAddItemNo(builder, itemNo):
    builder.PrependInt32Slot(3, itemNo, 0)

def AddItemNo(builder, itemNo):
    ShopRandomItemsAddItemNo(builder, itemNo)

def ShopRandomItemsAddItemAmount(builder, itemAmount):
    builder.PrependInt32Slot(4, itemAmount, 0)

def AddItemAmount(builder, itemAmount):
    ShopRandomItemsAddItemAmount(builder, itemAmount)

def ShopRandomItemsAddDrawLimit(builder, drawLimit):
    builder.PrependInt32Slot(5, drawLimit, 0)

def AddDrawLimit(builder, drawLimit):
    ShopRandomItemsAddDrawLimit(builder, drawLimit)

def ShopRandomItemsAddItemType(builder, itemType):
    builder.PrependInt32Slot(6, itemType, 0)

def AddItemType(builder, itemType):
    ShopRandomItemsAddItemType(builder, itemType)

def ShopRandomItemsAddDrawWeight(builder, drawWeight):
    builder.PrependInt32Slot(7, drawWeight, 0)

def AddDrawWeight(builder, drawWeight):
    ShopRandomItemsAddDrawWeight(builder, drawWeight)

def ShopRandomItemsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShopRandomItemsEnd(builder)
