# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShortcutPathTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShortcutPathTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShortcutPathTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShortcutPathTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShortcutPathTable
    def ShortcutPaths(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.ShortcutPath import ShortcutPath
            obj = ShortcutPath()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ShortcutPathTable
    def ShortcutPathsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShortcutPathTable
    def ShortcutPathsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ShortcutPathTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    ShortcutPathTableStart(builder)

def ShortcutPathTableAddShortcutPaths(builder, shortcutPaths):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shortcutPaths), 0)

def AddShortcutPaths(builder, shortcutPaths):
    ShortcutPathTableAddShortcutPaths(builder, shortcutPaths)

def ShortcutPathTableStartShortcutPathsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShortcutPathsVector(builder, numElems):
    return ShortcutPathTableStartShortcutPathsVector(builder, numElems)

def ShortcutPathTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShortcutPathTableEnd(builder)
