# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SignatureLevelCost(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SignatureLevelCost()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSignatureLevelCost(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SignatureLevelCost
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SignatureLevelCost
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureLevelCost
    def RaceGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureLevelCost
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureLevelCost
    def ItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureLevelCost
    def ItemAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def SignatureLevelCostStart(builder):
    builder.StartObject(5)

def Start(builder):
    SignatureLevelCostStart(builder)

def SignatureLevelCostAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    SignatureLevelCostAddNo(builder, no)

def SignatureLevelCostAddRaceGroup(builder, raceGroup):
    builder.PrependInt32Slot(1, raceGroup, 0)

def AddRaceGroup(builder, raceGroup):
    SignatureLevelCostAddRaceGroup(builder, raceGroup)

def SignatureLevelCostAddLevel(builder, level):
    builder.PrependInt32Slot(2, level, 0)

def AddLevel(builder, level):
    SignatureLevelCostAddLevel(builder, level)

def SignatureLevelCostAddItemNo(builder, itemNo):
    builder.PrependInt32Slot(3, itemNo, 0)

def AddItemNo(builder, itemNo):
    SignatureLevelCostAddItemNo(builder, itemNo)

def SignatureLevelCostAddItemAmount(builder, itemAmount):
    builder.PrependInt32Slot(4, itemAmount, 0)

def AddItemAmount(builder, itemAmount):
    SignatureLevelCostAddItemAmount(builder, itemAmount)

def SignatureLevelCostEnd(builder):
    return builder.EndObject()

def End(builder):
    return SignatureLevelCostEnd(builder)
