# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SignatureGradeTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SignatureGradeTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSignatureGradeTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SignatureGradeTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SignatureGradeTable
    def SignatureGrades(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SignatureGrade import SignatureGrade
            obj = SignatureGrade()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SignatureGradeTable
    def SignatureGradesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SignatureGradeTable
    def SignatureGradesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SignatureGradeTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SignatureGradeTableStart(builder)

def SignatureGradeTableAddSignatureGrades(builder, signatureGrades):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(signatureGrades), 0)

def AddSignatureGrades(builder, signatureGrades):
    SignatureGradeTableAddSignatureGrades(builder, signatureGrades)

def SignatureGradeTableStartSignatureGradesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSignatureGradesVector(builder, numElems):
    return SignatureGradeTableStartSignatureGradesVector(builder, numElems)

def SignatureGradeTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SignatureGradeTableEnd(builder)
