# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SignatureGrade(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SignatureGrade()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSignatureGrade(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SignatureGrade
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SignatureGrade
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def SignatureGrade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def SignatureMaxLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def NeedItemNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def ItemAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def CollectionPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def IconBgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SignatureGrade
    def SkillLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SignatureGrade
    def SignatureBgEffect(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SignatureGradeStart(builder):
    builder.StartObject(10)

def Start(builder):
    SignatureGradeStart(builder)

def SignatureGradeAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    SignatureGradeAddNo(builder, no)

def SignatureGradeAddGroup(builder, group):
    builder.PrependInt32Slot(1, group, 0)

def AddGroup(builder, group):
    SignatureGradeAddGroup(builder, group)

def SignatureGradeAddSignatureGrade(builder, signatureGrade):
    builder.PrependInt32Slot(2, signatureGrade, 0)

def AddSignatureGrade(builder, signatureGrade):
    SignatureGradeAddSignatureGrade(builder, signatureGrade)

def SignatureGradeAddSignatureMaxLevel(builder, signatureMaxLevel):
    builder.PrependInt32Slot(3, signatureMaxLevel, 0)

def AddSignatureMaxLevel(builder, signatureMaxLevel):
    SignatureGradeAddSignatureMaxLevel(builder, signatureMaxLevel)

def SignatureGradeAddNeedItemNo(builder, needItemNo):
    builder.PrependInt32Slot(4, needItemNo, 0)

def AddNeedItemNo(builder, needItemNo):
    SignatureGradeAddNeedItemNo(builder, needItemNo)

def SignatureGradeAddItemAmount(builder, itemAmount):
    builder.PrependInt32Slot(5, itemAmount, 0)

def AddItemAmount(builder, itemAmount):
    SignatureGradeAddItemAmount(builder, itemAmount)

def SignatureGradeAddCollectionPoint(builder, collectionPoint):
    builder.PrependInt32Slot(6, collectionPoint, 0)

def AddCollectionPoint(builder, collectionPoint):
    SignatureGradeAddCollectionPoint(builder, collectionPoint)

def SignatureGradeAddIconBgPath(builder, iconBgPath):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(iconBgPath), 0)

def AddIconBgPath(builder, iconBgPath):
    SignatureGradeAddIconBgPath(builder, iconBgPath)

def SignatureGradeAddSkillLevel(builder, skillLevel):
    builder.PrependInt32Slot(8, skillLevel, 0)

def AddSkillLevel(builder, skillLevel):
    SignatureGradeAddSkillLevel(builder, skillLevel)

def SignatureGradeAddSignatureBgEffect(builder, signatureBgEffect):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(signatureBgEffect), 0)

def AddSignatureBgEffect(builder, signatureBgEffect):
    SignatureGradeAddSignatureBgEffect(builder, signatureBgEffect)

def SignatureGradeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SignatureGradeEnd(builder)
