# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleRaidBossGroggyTrigger(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleRaidBossGroggyTrigger()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleRaidBossGroggyTrigger(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleRaidBossGroggyTrigger
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleRaidBossGroggyTrigger
    def SingleRaidBossNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode6(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode7(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode8(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode9(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def GroggySkillCode10(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Type1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Value1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SingleRaidBossGroggyTrigger
    def Type2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Value2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SingleRaidBossGroggyTrigger
    def Type3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Value3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SingleRaidBossGroggyTrigger
    def Type4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Value4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SingleRaidBossGroggyTrigger
    def Type5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def Value5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SingleRaidBossGroggyTrigger
    def RecoveryDuration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SingleRaidBossGroggyTrigger
    def SoundPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SingleRaidBossGroggyTriggerStart(builder):
    builder.StartObject(23)

def Start(builder):
    SingleRaidBossGroggyTriggerStart(builder)

def SingleRaidBossGroggyTriggerAddSingleRaidBossNo(builder, singleRaidBossNo):
    builder.PrependInt32Slot(0, singleRaidBossNo, 0)

def AddSingleRaidBossNo(builder, singleRaidBossNo):
    SingleRaidBossGroggyTriggerAddSingleRaidBossNo(builder, singleRaidBossNo)

def SingleRaidBossGroggyTriggerAddGroggySkillCode1(builder, groggySkillCode1):
    builder.PrependInt32Slot(1, groggySkillCode1, 0)

def AddGroggySkillCode1(builder, groggySkillCode1):
    SingleRaidBossGroggyTriggerAddGroggySkillCode1(builder, groggySkillCode1)

def SingleRaidBossGroggyTriggerAddGroggySkillCode2(builder, groggySkillCode2):
    builder.PrependInt32Slot(2, groggySkillCode2, 0)

def AddGroggySkillCode2(builder, groggySkillCode2):
    SingleRaidBossGroggyTriggerAddGroggySkillCode2(builder, groggySkillCode2)

def SingleRaidBossGroggyTriggerAddGroggySkillCode3(builder, groggySkillCode3):
    builder.PrependInt32Slot(3, groggySkillCode3, 0)

def AddGroggySkillCode3(builder, groggySkillCode3):
    SingleRaidBossGroggyTriggerAddGroggySkillCode3(builder, groggySkillCode3)

def SingleRaidBossGroggyTriggerAddGroggySkillCode4(builder, groggySkillCode4):
    builder.PrependInt32Slot(4, groggySkillCode4, 0)

def AddGroggySkillCode4(builder, groggySkillCode4):
    SingleRaidBossGroggyTriggerAddGroggySkillCode4(builder, groggySkillCode4)

def SingleRaidBossGroggyTriggerAddGroggySkillCode5(builder, groggySkillCode5):
    builder.PrependInt32Slot(5, groggySkillCode5, 0)

def AddGroggySkillCode5(builder, groggySkillCode5):
    SingleRaidBossGroggyTriggerAddGroggySkillCode5(builder, groggySkillCode5)

def SingleRaidBossGroggyTriggerAddGroggySkillCode6(builder, groggySkillCode6):
    builder.PrependInt32Slot(6, groggySkillCode6, 0)

def AddGroggySkillCode6(builder, groggySkillCode6):
    SingleRaidBossGroggyTriggerAddGroggySkillCode6(builder, groggySkillCode6)

def SingleRaidBossGroggyTriggerAddGroggySkillCode7(builder, groggySkillCode7):
    builder.PrependInt32Slot(7, groggySkillCode7, 0)

def AddGroggySkillCode7(builder, groggySkillCode7):
    SingleRaidBossGroggyTriggerAddGroggySkillCode7(builder, groggySkillCode7)

def SingleRaidBossGroggyTriggerAddGroggySkillCode8(builder, groggySkillCode8):
    builder.PrependInt32Slot(8, groggySkillCode8, 0)

def AddGroggySkillCode8(builder, groggySkillCode8):
    SingleRaidBossGroggyTriggerAddGroggySkillCode8(builder, groggySkillCode8)

def SingleRaidBossGroggyTriggerAddGroggySkillCode9(builder, groggySkillCode9):
    builder.PrependInt32Slot(9, groggySkillCode9, 0)

def AddGroggySkillCode9(builder, groggySkillCode9):
    SingleRaidBossGroggyTriggerAddGroggySkillCode9(builder, groggySkillCode9)

def SingleRaidBossGroggyTriggerAddGroggySkillCode10(builder, groggySkillCode10):
    builder.PrependInt32Slot(10, groggySkillCode10, 0)

def AddGroggySkillCode10(builder, groggySkillCode10):
    SingleRaidBossGroggyTriggerAddGroggySkillCode10(builder, groggySkillCode10)

def SingleRaidBossGroggyTriggerAddType1(builder, type1):
    builder.PrependInt32Slot(11, type1, 0)

def AddType1(builder, type1):
    SingleRaidBossGroggyTriggerAddType1(builder, type1)

def SingleRaidBossGroggyTriggerAddValue1(builder, value1):
    builder.PrependFloat32Slot(12, value1, 0.0)

def AddValue1(builder, value1):
    SingleRaidBossGroggyTriggerAddValue1(builder, value1)

def SingleRaidBossGroggyTriggerAddType2(builder, type2):
    builder.PrependInt32Slot(13, type2, 0)

def AddType2(builder, type2):
    SingleRaidBossGroggyTriggerAddType2(builder, type2)

def SingleRaidBossGroggyTriggerAddValue2(builder, value2):
    builder.PrependFloat32Slot(14, value2, 0.0)

def AddValue2(builder, value2):
    SingleRaidBossGroggyTriggerAddValue2(builder, value2)

def SingleRaidBossGroggyTriggerAddType3(builder, type3):
    builder.PrependInt32Slot(15, type3, 0)

def AddType3(builder, type3):
    SingleRaidBossGroggyTriggerAddType3(builder, type3)

def SingleRaidBossGroggyTriggerAddValue3(builder, value3):
    builder.PrependFloat32Slot(16, value3, 0.0)

def AddValue3(builder, value3):
    SingleRaidBossGroggyTriggerAddValue3(builder, value3)

def SingleRaidBossGroggyTriggerAddType4(builder, type4):
    builder.PrependInt32Slot(17, type4, 0)

def AddType4(builder, type4):
    SingleRaidBossGroggyTriggerAddType4(builder, type4)

def SingleRaidBossGroggyTriggerAddValue4(builder, value4):
    builder.PrependFloat32Slot(18, value4, 0.0)

def AddValue4(builder, value4):
    SingleRaidBossGroggyTriggerAddValue4(builder, value4)

def SingleRaidBossGroggyTriggerAddType5(builder, type5):
    builder.PrependInt32Slot(19, type5, 0)

def AddType5(builder, type5):
    SingleRaidBossGroggyTriggerAddType5(builder, type5)

def SingleRaidBossGroggyTriggerAddValue5(builder, value5):
    builder.PrependFloat32Slot(20, value5, 0.0)

def AddValue5(builder, value5):
    SingleRaidBossGroggyTriggerAddValue5(builder, value5)

def SingleRaidBossGroggyTriggerAddRecoveryDuration(builder, recoveryDuration):
    builder.PrependInt32Slot(21, recoveryDuration, 0)

def AddRecoveryDuration(builder, recoveryDuration):
    SingleRaidBossGroggyTriggerAddRecoveryDuration(builder, recoveryDuration)

def SingleRaidBossGroggyTriggerAddSoundPath(builder, soundPath):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(soundPath), 0)

def AddSoundPath(builder, soundPath):
    SingleRaidBossGroggyTriggerAddSoundPath(builder, soundPath)

def SingleRaidBossGroggyTriggerEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleRaidBossGroggyTriggerEnd(builder)
