# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleRaidRankRewardTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleRaidRankRewardTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleRaidRankRewardTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleRaidRankRewardTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleRaidRankRewardTable
    def SingleRaidRankRewards(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SingleRaidRankReward import SingleRaidRankReward
            obj = SingleRaidRankReward()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SingleRaidRankRewardTable
    def SingleRaidRankRewardsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SingleRaidRankRewardTable
    def SingleRaidRankRewardsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SingleRaidRankRewardTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SingleRaidRankRewardTableStart(builder)

def SingleRaidRankRewardTableAddSingleRaidRankRewards(builder, singleRaidRankRewards):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(singleRaidRankRewards), 0)

def AddSingleRaidRankRewards(builder, singleRaidRankRewards):
    SingleRaidRankRewardTableAddSingleRaidRankRewards(builder, singleRaidRankRewards)

def SingleRaidRankRewardTableStartSingleRaidRankRewardsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSingleRaidRankRewardsVector(builder, numElems):
    return SingleRaidRankRewardTableStartSingleRaidRankRewardsVector(builder, numElems)

def SingleRaidRankRewardTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleRaidRankRewardTableEnd(builder)
