# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleRaidSeasonGimmickTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleRaidSeasonGimmickTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleRaidSeasonGimmickTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleRaidSeasonGimmickTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleRaidSeasonGimmickTable
    def SingleRaidSeasonGimmicks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SingleRaidSeasonGimmick import SingleRaidSeasonGimmick
            obj = SingleRaidSeasonGimmick()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SingleRaidSeasonGimmickTable
    def SingleRaidSeasonGimmicksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SingleRaidSeasonGimmickTable
    def SingleRaidSeasonGimmicksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SingleRaidSeasonGimmickTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SingleRaidSeasonGimmickTableStart(builder)

def SingleRaidSeasonGimmickTableAddSingleRaidSeasonGimmicks(builder, singleRaidSeasonGimmicks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(singleRaidSeasonGimmicks), 0)

def AddSingleRaidSeasonGimmicks(builder, singleRaidSeasonGimmicks):
    SingleRaidSeasonGimmickTableAddSingleRaidSeasonGimmicks(builder, singleRaidSeasonGimmicks)

def SingleRaidSeasonGimmickTableStartSingleRaidSeasonGimmicksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSingleRaidSeasonGimmicksVector(builder, numElems):
    return SingleRaidSeasonGimmickTableStartSingleRaidSeasonGimmicksVector(builder, numElems)

def SingleRaidSeasonGimmickTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleRaidSeasonGimmickTableEnd(builder)
