# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkillBuffResistTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkillBuffResistTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkillBuffResistTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkillBuffResistTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkillBuffResistTable
    def SkillBuffResists(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SkillBuffResist import SkillBuffResist
            obj = SkillBuffResist()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SkillBuffResistTable
    def SkillBuffResistsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkillBuffResistTable
    def SkillBuffResistsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SkillBuffResistTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SkillBuffResistTableStart(builder)

def SkillBuffResistTableAddSkillBuffResists(builder, skillBuffResists):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(skillBuffResists), 0)

def AddSkillBuffResists(builder, skillBuffResists):
    SkillBuffResistTableAddSkillBuffResists(builder, skillBuffResists)

def SkillBuffResistTableStartSkillBuffResistsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSkillBuffResistsVector(builder, numElems):
    return SkillBuffResistTableStartSkillBuffResistsVector(builder, numElems)

def SkillBuffResistTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkillBuffResistTableEnd(builder)
