# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkillSummonTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkillSummonTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkillSummonTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkillSummonTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkillSummonTable
    def SkillSummons(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SkillSummon import SkillSummon
            obj = SkillSummon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SkillSummonTable
    def SkillSummonsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkillSummonTable
    def SkillSummonsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SkillSummonTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SkillSummonTableStart(builder)

def SkillSummonTableAddSkillSummons(builder, skillSummons):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(skillSummons), 0)

def AddSkillSummons(builder, skillSummons):
    SkillSummonTableAddSkillSummons(builder, skillSummons)

def SkillSummonTableStartSkillSummonsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSkillSummonsVector(builder, numElems):
    return SkillSummonTableStartSkillSummonsVector(builder, numElems)

def SkillSummonTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkillSummonTableEnd(builder)
