# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkillConditionTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkillConditionTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkillConditionTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkillConditionTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkillConditionTable
    def SkillConditions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.SkillCondition import SkillCondition
            obj = SkillCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SkillConditionTable
    def SkillConditionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkillConditionTable
    def SkillConditionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SkillConditionTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    SkillConditionTableStart(builder)

def SkillConditionTableAddSkillConditions(builder, skillConditions):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(skillConditions), 0)

def AddSkillConditions(builder, skillConditions):
    SkillConditionTableAddSkillConditions(builder, skillConditions)

def SkillConditionTableStartSkillConditionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSkillConditionsVector(builder, numElems):
    return SkillConditionTableStartSkillConditionsVector(builder, numElems)

def SkillConditionTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkillConditionTableEnd(builder)
