# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Soullink_CollectionTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Soullink_CollectionTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSoullink_CollectionTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Soullink_CollectionTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Soullink_CollectionTable
    def Soullink_collections(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Soullink_Collection import Soullink_Collection
            obj = Soullink_Collection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Soullink_CollectionTable
    def Soullink_collectionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Soullink_CollectionTable
    def Soullink_collectionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Soullink_CollectionTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    Soullink_CollectionTableStart(builder)

def Soullink_CollectionTableAddSoullink_collections(builder, soullink_collections):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(soullink_collections), 0)

def AddSoullink_collections(builder, soullink_collections):
    Soullink_CollectionTableAddSoullink_collections(builder, soullink_collections)

def Soullink_CollectionTableStartSoullink_collectionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSoullink_collectionsVector(builder, numElems):
    return Soullink_CollectionTableStartSoullink_collectionsVector(builder, numElems)

def Soullink_CollectionTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return Soullink_CollectionTableEnd(builder)
