# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Sound(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Sound()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSound(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Sound
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sound
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sound
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sound
    def SoundType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Sound
    def MixerGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Sound
    def Kor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sound
    def Jpn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sound
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SoundStart(builder):
    builder.StartObject(7)

def Start(builder):
    SoundStart(builder)

def SoundAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    SoundAddNo(builder, no)

def SoundAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SoundAddName(builder, name)

def SoundAddSoundType(builder, soundType):
    builder.PrependInt8Slot(2, soundType, 0)

def AddSoundType(builder, soundType):
    SoundAddSoundType(builder, soundType)

def SoundAddMixerGroup(builder, mixerGroup):
    builder.PrependInt8Slot(3, mixerGroup, 0)

def AddMixerGroup(builder, mixerGroup):
    SoundAddMixerGroup(builder, mixerGroup)

def SoundAddKor(builder, kor):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(kor), 0)

def AddKor(builder, kor):
    SoundAddKor(builder, kor)

def SoundAddJpn(builder, jpn):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(jpn), 0)

def AddJpn(builder, jpn):
    SoundAddJpn(builder, jpn)

def SoundAddVolume(builder, volume):
    builder.PrependFloat32Slot(6, volume, 0.0)

def AddVolume(builder, volume):
    SoundAddVolume(builder, volume)

def SoundEnd(builder):
    return builder.EndObject()

def End(builder):
    return SoundEnd(builder)
