# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StageEquipTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageEquipTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageEquipTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StageEquipTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageEquipTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.StageEquip import StageEquip
            obj = StageEquip()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageEquipTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageEquipTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StageEquipTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    StageEquipTableStart(builder)

def StageEquipTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    StageEquipTableAddJson(builder, json)

def StageEquipTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return StageEquipTableStartJsonVector(builder, numElems)

def StageEquipTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageEquipTableEnd(builder)
