# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageTable
    def Stages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Stage import Stage
            obj = Stage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageTable
    def StagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageTable
    def StagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StageTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    StageTableStart(builder)

def StageTableAddStages(builder, stages):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stages), 0)

def AddStages(builder, stages):
    StageTableAddStages(builder, stages)

def StageTableStartStagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStagesVector(builder, numElems):
    return StageTableStartStagesVector(builder, numElems)

def StageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageTableEnd(builder)
