# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StageBattle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageBattle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageBattle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StageBattle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageBattle
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def TeamNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroNo1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroGrade1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def Level1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroEquip1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def UltimateAutosetting1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroNo2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroGrade2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def Level2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroEquip2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def UltimateAutosetting2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroNo3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroGrade3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def Level3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroEquip3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def UltimateAutosetting3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroNo4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroGrade4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def Level4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroEquip4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def UltimateAutosetting4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroNo5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroGrade5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def Level5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def HeroEquip5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def UltimateAutosetting5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def FormationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def SignatureLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StageBattle
    def SignatureSkillLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def StageBattleStart(builder):
    builder.StartObject(31)

def Start(builder):
    StageBattleStart(builder)

def StageBattleAddIndex(builder, index):
    builder.PrependInt32Slot(0, index, 0)

def AddIndex(builder, index):
    StageBattleAddIndex(builder, index)

def StageBattleAddNo(builder, no):
    builder.PrependInt32Slot(1, no, 0)

def AddNo(builder, no):
    StageBattleAddNo(builder, no)

def StageBattleAddTeamNo(builder, teamNo):
    builder.PrependInt32Slot(2, teamNo, 0)

def AddTeamNo(builder, teamNo):
    StageBattleAddTeamNo(builder, teamNo)

def StageBattleAddHeroNo1(builder, heroNo1):
    builder.PrependInt32Slot(3, heroNo1, 0)

def AddHeroNo1(builder, heroNo1):
    StageBattleAddHeroNo1(builder, heroNo1)

def StageBattleAddHeroGrade1(builder, heroGrade1):
    builder.PrependInt32Slot(4, heroGrade1, 0)

def AddHeroGrade1(builder, heroGrade1):
    StageBattleAddHeroGrade1(builder, heroGrade1)

def StageBattleAddLevel1(builder, level1):
    builder.PrependInt32Slot(5, level1, 0)

def AddLevel1(builder, level1):
    StageBattleAddLevel1(builder, level1)

def StageBattleAddHeroEquip1(builder, heroEquip1):
    builder.PrependInt32Slot(6, heroEquip1, 0)

def AddHeroEquip1(builder, heroEquip1):
    StageBattleAddHeroEquip1(builder, heroEquip1)

def StageBattleAddUltimateAutosetting1(builder, ultimateAutosetting1):
    builder.PrependInt32Slot(7, ultimateAutosetting1, 0)

def AddUltimateAutosetting1(builder, ultimateAutosetting1):
    StageBattleAddUltimateAutosetting1(builder, ultimateAutosetting1)

def StageBattleAddHeroNo2(builder, heroNo2):
    builder.PrependInt32Slot(8, heroNo2, 0)

def AddHeroNo2(builder, heroNo2):
    StageBattleAddHeroNo2(builder, heroNo2)

def StageBattleAddHeroGrade2(builder, heroGrade2):
    builder.PrependInt32Slot(9, heroGrade2, 0)

def AddHeroGrade2(builder, heroGrade2):
    StageBattleAddHeroGrade2(builder, heroGrade2)

def StageBattleAddLevel2(builder, level2):
    builder.PrependInt32Slot(10, level2, 0)

def AddLevel2(builder, level2):
    StageBattleAddLevel2(builder, level2)

def StageBattleAddHeroEquip2(builder, heroEquip2):
    builder.PrependInt32Slot(11, heroEquip2, 0)

def AddHeroEquip2(builder, heroEquip2):
    StageBattleAddHeroEquip2(builder, heroEquip2)

def StageBattleAddUltimateAutosetting2(builder, ultimateAutosetting2):
    builder.PrependInt32Slot(12, ultimateAutosetting2, 0)

def AddUltimateAutosetting2(builder, ultimateAutosetting2):
    StageBattleAddUltimateAutosetting2(builder, ultimateAutosetting2)

def StageBattleAddHeroNo3(builder, heroNo3):
    builder.PrependInt32Slot(13, heroNo3, 0)

def AddHeroNo3(builder, heroNo3):
    StageBattleAddHeroNo3(builder, heroNo3)

def StageBattleAddHeroGrade3(builder, heroGrade3):
    builder.PrependInt32Slot(14, heroGrade3, 0)

def AddHeroGrade3(builder, heroGrade3):
    StageBattleAddHeroGrade3(builder, heroGrade3)

def StageBattleAddLevel3(builder, level3):
    builder.PrependInt32Slot(15, level3, 0)

def AddLevel3(builder, level3):
    StageBattleAddLevel3(builder, level3)

def StageBattleAddHeroEquip3(builder, heroEquip3):
    builder.PrependInt32Slot(16, heroEquip3, 0)

def AddHeroEquip3(builder, heroEquip3):
    StageBattleAddHeroEquip3(builder, heroEquip3)

def StageBattleAddUltimateAutosetting3(builder, ultimateAutosetting3):
    builder.PrependInt32Slot(17, ultimateAutosetting3, 0)

def AddUltimateAutosetting3(builder, ultimateAutosetting3):
    StageBattleAddUltimateAutosetting3(builder, ultimateAutosetting3)

def StageBattleAddHeroNo4(builder, heroNo4):
    builder.PrependInt32Slot(18, heroNo4, 0)

def AddHeroNo4(builder, heroNo4):
    StageBattleAddHeroNo4(builder, heroNo4)

def StageBattleAddHeroGrade4(builder, heroGrade4):
    builder.PrependInt32Slot(19, heroGrade4, 0)

def AddHeroGrade4(builder, heroGrade4):
    StageBattleAddHeroGrade4(builder, heroGrade4)

def StageBattleAddLevel4(builder, level4):
    builder.PrependInt32Slot(20, level4, 0)

def AddLevel4(builder, level4):
    StageBattleAddLevel4(builder, level4)

def StageBattleAddHeroEquip4(builder, heroEquip4):
    builder.PrependInt32Slot(21, heroEquip4, 0)

def AddHeroEquip4(builder, heroEquip4):
    StageBattleAddHeroEquip4(builder, heroEquip4)

def StageBattleAddUltimateAutosetting4(builder, ultimateAutosetting4):
    builder.PrependInt32Slot(22, ultimateAutosetting4, 0)

def AddUltimateAutosetting4(builder, ultimateAutosetting4):
    StageBattleAddUltimateAutosetting4(builder, ultimateAutosetting4)

def StageBattleAddHeroNo5(builder, heroNo5):
    builder.PrependInt32Slot(23, heroNo5, 0)

def AddHeroNo5(builder, heroNo5):
    StageBattleAddHeroNo5(builder, heroNo5)

def StageBattleAddHeroGrade5(builder, heroGrade5):
    builder.PrependInt32Slot(24, heroGrade5, 0)

def AddHeroGrade5(builder, heroGrade5):
    StageBattleAddHeroGrade5(builder, heroGrade5)

def StageBattleAddLevel5(builder, level5):
    builder.PrependInt32Slot(25, level5, 0)

def AddLevel5(builder, level5):
    StageBattleAddLevel5(builder, level5)

def StageBattleAddHeroEquip5(builder, heroEquip5):
    builder.PrependInt32Slot(26, heroEquip5, 0)

def AddHeroEquip5(builder, heroEquip5):
    StageBattleAddHeroEquip5(builder, heroEquip5)

def StageBattleAddUltimateAutosetting5(builder, ultimateAutosetting5):
    builder.PrependInt32Slot(27, ultimateAutosetting5, 0)

def AddUltimateAutosetting5(builder, ultimateAutosetting5):
    StageBattleAddUltimateAutosetting5(builder, ultimateAutosetting5)

def StageBattleAddFormationType(builder, formationType):
    builder.PrependInt32Slot(28, formationType, 0)

def AddFormationType(builder, formationType):
    StageBattleAddFormationType(builder, formationType)

def StageBattleAddSignatureLevel(builder, signatureLevel):
    builder.PrependInt32Slot(29, signatureLevel, 0)

def AddSignatureLevel(builder, signatureLevel):
    StageBattleAddSignatureLevel(builder, signatureLevel)

def StageBattleAddSignatureSkillLevel(builder, signatureSkillLevel):
    builder.PrependInt32Slot(30, signatureSkillLevel, 0)

def AddSignatureSkillLevel(builder, signatureSkillLevel):
    StageBattleAddSignatureSkillLevel(builder, signatureSkillLevel)

def StageBattleEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageBattleEnd(builder)
