# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StickerTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StickerTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStickerTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StickerTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StickerTable
    def Stickers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.Sticker import Sticker
            obj = Sticker()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StickerTable
    def StickersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StickerTable
    def StickersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StickerTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    StickerTableStart(builder)

def StickerTableAddStickers(builder, stickers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stickers), 0)

def AddStickers(builder, stickers):
    StickerTableAddStickers(builder, stickers)

def StickerTableStartStickersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStickersVector(builder, numElems):
    return StickerTableStartStickersVector(builder, numElems)

def StickerTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return StickerTableEnd(builder)
