# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StringDungeonTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StringDungeonTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStringDungeonTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StringDungeonTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StringDungeonTable
    def StringDungeons(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.StringDungeon import StringDungeon
            obj = StringDungeon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StringDungeonTable
    def StringDungeonsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StringDungeonTable
    def StringDungeonsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StringDungeonTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    StringDungeonTableStart(builder)

def StringDungeonTableAddStringDungeons(builder, stringDungeons):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stringDungeons), 0)

def AddStringDungeons(builder, stringDungeons):
    StringDungeonTableAddStringDungeons(builder, stringDungeons)

def StringDungeonTableStartStringDungeonsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStringDungeonsVector(builder, numElems):
    return StringDungeonTableStartStringDungeonsVector(builder, numElems)

def StringDungeonTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return StringDungeonTableEnd(builder)
