# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StringSkillTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StringSkillTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStringSkillTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StringSkillTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StringSkillTable
    def StringSkills(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.StringSkill import StringSkill
            obj = StringSkill()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StringSkillTable
    def StringSkillsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StringSkillTable
    def StringSkillsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StringSkillTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    StringSkillTableStart(builder)

def StringSkillTableAddStringSkills(builder, stringSkills):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stringSkills), 0)

def AddStringSkills(builder, stringSkills):
    StringSkillTableAddStringSkills(builder, stringSkills)

def StringSkillTableStartStringSkillsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStringSkillsVector(builder, numElems):
    return StringSkillTableStartStringSkillsVector(builder, numElems)

def StringSkillTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return StringSkillTableEnd(builder)
