# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TalkEventDesc(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkEventDesc()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkEventDesc(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkEventDesc
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkEventDesc
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEventDesc
    def EventNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEventDesc
    def Order(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEventDesc
    def DescList(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TalkEventDescStart(builder):
    builder.StartObject(4)

def Start(builder):
    TalkEventDescStart(builder)

def TalkEventDescAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    TalkEventDescAddNo(builder, no)

def TalkEventDescAddEventNo(builder, eventNo):
    builder.PrependInt32Slot(1, eventNo, 0)

def AddEventNo(builder, eventNo):
    TalkEventDescAddEventNo(builder, eventNo)

def TalkEventDescAddOrder(builder, order):
    builder.PrependInt32Slot(2, order, 0)

def AddOrder(builder, order):
    TalkEventDescAddOrder(builder, order)

def TalkEventDescAddDescList(builder, descList):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(descList), 0)

def AddDescList(builder, descList):
    TalkEventDescAddDescList(builder, descList)

def TalkEventDescEnd(builder):
    return builder.EndObject()

def End(builder):
    return TalkEventDescEnd(builder)
