# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TalkActor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkActor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkActor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkActor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkActor
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkActor
    def NameSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkActor
    def PrefabPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkActor
    def Portrait512Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkActor
    def Portrait128Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkActor
    def CostumePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkActor
    def ControllerPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkActor
    def PortraitReverse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkActor
    def PositionX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TalkActor
    def PositionY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TalkActor
    def PositionZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TalkActor
    def PositionScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TalkActorStart(builder):
    builder.StartObject(12)

def Start(builder):
    TalkActorStart(builder)

def TalkActorAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    TalkActorAddNo(builder, no)

def TalkActorAddNameSno(builder, nameSno):
    builder.PrependInt32Slot(1, nameSno, 0)

def AddNameSno(builder, nameSno):
    TalkActorAddNameSno(builder, nameSno)

def TalkActorAddPrefabPath(builder, prefabPath):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prefabPath), 0)

def AddPrefabPath(builder, prefabPath):
    TalkActorAddPrefabPath(builder, prefabPath)

def TalkActorAddPortrait512Path(builder, portrait512Path):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(portrait512Path), 0)

def AddPortrait512Path(builder, portrait512Path):
    TalkActorAddPortrait512Path(builder, portrait512Path)

def TalkActorAddPortrait128Path(builder, portrait128Path):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(portrait128Path), 0)

def AddPortrait128Path(builder, portrait128Path):
    TalkActorAddPortrait128Path(builder, portrait128Path)

def TalkActorAddCostumePath(builder, costumePath):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(costumePath), 0)

def AddCostumePath(builder, costumePath):
    TalkActorAddCostumePath(builder, costumePath)

def TalkActorAddControllerPath(builder, controllerPath):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(controllerPath), 0)

def AddControllerPath(builder, controllerPath):
    TalkActorAddControllerPath(builder, controllerPath)

def TalkActorAddPortraitReverse(builder, portraitReverse):
    builder.PrependInt32Slot(7, portraitReverse, 0)

def AddPortraitReverse(builder, portraitReverse):
    TalkActorAddPortraitReverse(builder, portraitReverse)

def TalkActorAddPositionX(builder, positionX):
    builder.PrependFloat32Slot(8, positionX, 0.0)

def AddPositionX(builder, positionX):
    TalkActorAddPositionX(builder, positionX)

def TalkActorAddPositionY(builder, positionY):
    builder.PrependFloat32Slot(9, positionY, 0.0)

def AddPositionY(builder, positionY):
    TalkActorAddPositionY(builder, positionY)

def TalkActorAddPositionZ(builder, positionZ):
    builder.PrependFloat32Slot(10, positionZ, 0.0)

def AddPositionZ(builder, positionZ):
    TalkActorAddPositionZ(builder, positionZ)

def TalkActorAddPositionScale(builder, positionScale):
    builder.PrependFloat32Slot(11, positionScale, 0.0)

def AddPositionScale(builder, positionScale):
    TalkActorAddPositionScale(builder, positionScale)

def TalkActorEnd(builder):
    return builder.EndObject()

def End(builder):
    return TalkActorEnd(builder)
