# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TalkStageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkStageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkStageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkStageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkStageTable
    def TalkStages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.TalkStage import TalkStage
            obj = TalkStage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TalkStageTable
    def TalkStagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TalkStageTable
    def TalkStagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TalkStageTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TalkStageTableStart(builder)

def TalkStageTableAddTalkStages(builder, talkStages):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(talkStages), 0)

def AddTalkStages(builder, talkStages):
    TalkStageTableAddTalkStages(builder, talkStages)

def TalkStageTableStartTalkStagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTalkStagesVector(builder, numElems):
    return TalkStageTableStartTalkStagesVector(builder, numElems)

def TalkStageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TalkStageTableEnd(builder)
