# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TalkCutSceneTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkCutSceneTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkCutSceneTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkCutSceneTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkCutSceneTable
    def TalkCutScenes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.TalkCutScene import TalkCutScene
            obj = TalkCutScene()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TalkCutSceneTable
    def TalkCutScenesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TalkCutSceneTable
    def TalkCutScenesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TalkCutSceneTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TalkCutSceneTableStart(builder)

def TalkCutSceneTableAddTalkCutScenes(builder, talkCutScenes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(talkCutScenes), 0)

def AddTalkCutScenes(builder, talkCutScenes):
    TalkCutSceneTableAddTalkCutScenes(builder, talkCutScenes)

def TalkCutSceneTableStartTalkCutScenesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTalkCutScenesVector(builder, numElems):
    return TalkCutSceneTableStartTalkCutScenesVector(builder, numElems)

def TalkCutSceneTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TalkCutSceneTableEnd(builder)
