# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TalkEmotion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkEmotion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkEmotion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkEmotion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkEmotion
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEmotion
    def ActorNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEmotion
    def EmotionName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkEmotion
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TalkEmotion
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TalkEmotionStart(builder):
    builder.StartObject(5)

def Start(builder):
    TalkEmotionStart(builder)

def TalkEmotionAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    TalkEmotionAddNo(builder, no)

def TalkEmotionAddActorNo(builder, actorNo):
    builder.PrependInt32Slot(1, actorNo, 0)

def AddActorNo(builder, actorNo):
    TalkEmotionAddActorNo(builder, actorNo)

def TalkEmotionAddEmotionName(builder, emotionName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(emotionName), 0)

def AddEmotionName(builder, emotionName):
    TalkEmotionAddEmotionName(builder, emotionName)

def TalkEmotionAddIndex(builder, index):
    builder.PrependInt32Slot(3, index, 0)

def AddIndex(builder, index):
    TalkEmotionAddIndex(builder, index)

def TalkEmotionAddWeight(builder, weight):
    builder.PrependInt32Slot(4, weight, 0)

def AddWeight(builder, weight):
    TalkEmotionAddWeight(builder, weight)

def TalkEmotionEnd(builder):
    return builder.EndObject()

def End(builder):
    return TalkEmotionEnd(builder)
