# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TowerExtend(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TowerExtend()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTowerExtend(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TowerExtend
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TowerExtend
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TowerExtend
    def ReqHero(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TowerExtend
    def BgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TowerExtend
    def ReqClearStage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TowerExtend
    def ReqString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TowerExtendStart(builder):
    builder.StartObject(5)

def Start(builder):
    TowerExtendStart(builder)

def TowerExtendAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    TowerExtendAddNo(builder, no)

def TowerExtendAddReqHero(builder, reqHero):
    builder.PrependInt32Slot(1, reqHero, 0)

def AddReqHero(builder, reqHero):
    TowerExtendAddReqHero(builder, reqHero)

def TowerExtendAddBgPath(builder, bgPath):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bgPath), 0)

def AddBgPath(builder, bgPath):
    TowerExtendAddBgPath(builder, bgPath)

def TowerExtendAddReqClearStage(builder, reqClearStage):
    builder.PrependInt32Slot(3, reqClearStage, 0)

def AddReqClearStage(builder, reqClearStage):
    TowerExtendAddReqClearStage(builder, reqClearStage)

def TowerExtendAddReqString(builder, reqString):
    builder.PrependInt32Slot(4, reqString, 0)

def AddReqString(builder, reqString):
    TowerExtendAddReqString(builder, reqString)

def TowerExtendEnd(builder):
    return builder.EndObject()

def End(builder):
    return TowerExtendEnd(builder)
