# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TowerEnemyTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TowerEnemyTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTowerEnemyTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TowerEnemyTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TowerEnemyTable
    def TowerEnemys(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.TowerEnemy import TowerEnemy
            obj = TowerEnemy()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TowerEnemyTable
    def TowerEnemysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TowerEnemyTable
    def TowerEnemysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TowerEnemyTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TowerEnemyTableStart(builder)

def TowerEnemyTableAddTowerEnemys(builder, towerEnemys):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(towerEnemys), 0)

def AddTowerEnemys(builder, towerEnemys):
    TowerEnemyTableAddTowerEnemys(builder, towerEnemys)

def TowerEnemyTableStartTowerEnemysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTowerEnemysVector(builder, numElems):
    return TowerEnemyTableStartTowerEnemysVector(builder, numElems)

def TowerEnemyTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TowerEnemyTableEnd(builder)
