# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TownWarpTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TownWarpTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTownWarpTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TownWarpTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TownWarpTable
    def TownWarps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.TownWarp import TownWarp
            obj = TownWarp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TownWarpTable
    def TownWarpsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TownWarpTable
    def TownWarpsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TownWarpTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TownWarpTableStart(builder)

def TownWarpTableAddTownWarps(builder, townWarps):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(townWarps), 0)

def AddTownWarps(builder, townWarps):
    TownWarpTableAddTownWarps(builder, townWarps)

def TownWarpTableStartTownWarpsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTownWarpsVector(builder, numElems):
    return TownWarpTableStartTownWarpsVector(builder, numElems)

def TownWarpTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TownWarpTableEnd(builder)
