# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TownEnemyTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TownEnemyTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTownEnemyTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TownEnemyTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TownEnemyTable
    def TownEnemys(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.TownEnemy import TownEnemy
            obj = TownEnemy()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TownEnemyTable
    def TownEnemysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TownEnemyTable
    def TownEnemysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TownEnemyTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TownEnemyTableStart(builder)

def TownEnemyTableAddTownEnemys(builder, townEnemys):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(townEnemys), 0)

def AddTownEnemys(builder, townEnemys):
    TownEnemyTableAddTownEnemys(builder, townEnemys)

def TownEnemyTableStartTownEnemysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTownEnemysVector(builder, numElems):
    return TownEnemyTableStartTownEnemysVector(builder, numElems)

def TownEnemyTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TownEnemyTableEnd(builder)
