# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TripKeyword(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TripKeyword()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTripKeyword(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TripKeyword
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TripKeyword
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def HeroNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def KeywordGrade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def KeywordString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def KeywordType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def KeywordSource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TripKeyword
    def KeywordGetDetails(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TripKeywordStart(builder):
    builder.StartObject(7)

def Start(builder):
    TripKeywordStart(builder)

def TripKeywordAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    TripKeywordAddNo(builder, no)

def TripKeywordAddHeroNo(builder, heroNo):
    builder.PrependInt32Slot(1, heroNo, 0)

def AddHeroNo(builder, heroNo):
    TripKeywordAddHeroNo(builder, heroNo)

def TripKeywordAddKeywordGrade(builder, keywordGrade):
    builder.PrependInt32Slot(2, keywordGrade, 0)

def AddKeywordGrade(builder, keywordGrade):
    TripKeywordAddKeywordGrade(builder, keywordGrade)

def TripKeywordAddKeywordString(builder, keywordString):
    builder.PrependInt32Slot(3, keywordString, 0)

def AddKeywordString(builder, keywordString):
    TripKeywordAddKeywordString(builder, keywordString)

def TripKeywordAddKeywordType(builder, keywordType):
    builder.PrependInt32Slot(4, keywordType, 0)

def AddKeywordType(builder, keywordType):
    TripKeywordAddKeywordType(builder, keywordType)

def TripKeywordAddKeywordSource(builder, keywordSource):
    builder.PrependInt32Slot(5, keywordSource, 0)

def AddKeywordSource(builder, keywordSource):
    TripKeywordAddKeywordSource(builder, keywordSource)

def TripKeywordAddKeywordGetDetails(builder, keywordGetDetails):
    builder.PrependInt32Slot(6, keywordGetDetails, 0)

def AddKeywordGetDetails(builder, keywordGetDetails):
    TripKeywordAddKeywordGetDetails(builder, keywordGetDetails)

def TripKeywordEnd(builder):
    return builder.EndObject()

def End(builder):
    return TripKeywordEnd(builder)
