# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldRaidPartnerBuffTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldRaidPartnerBuffTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldRaidPartnerBuffTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldRaidPartnerBuffTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldRaidPartnerBuffTable
    def WorldRaidPartnerBuffs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.WorldRaidPartnerBuff import WorldRaidPartnerBuff
            obj = WorldRaidPartnerBuff()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldRaidPartnerBuffTable
    def WorldRaidPartnerBuffsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldRaidPartnerBuffTable
    def WorldRaidPartnerBuffsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WorldRaidPartnerBuffTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    WorldRaidPartnerBuffTableStart(builder)

def WorldRaidPartnerBuffTableAddWorldRaidPartnerBuffs(builder, worldRaidPartnerBuffs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(worldRaidPartnerBuffs), 0)

def AddWorldRaidPartnerBuffs(builder, worldRaidPartnerBuffs):
    WorldRaidPartnerBuffTableAddWorldRaidPartnerBuffs(builder, worldRaidPartnerBuffs)

def WorldRaidPartnerBuffTableStartWorldRaidPartnerBuffsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWorldRaidPartnerBuffsVector(builder, numElems):
    return WorldRaidPartnerBuffTableStartWorldRaidPartnerBuffsVector(builder, numElems)

def WorldRaidPartnerBuffTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldRaidPartnerBuffTableEnd(builder)
