# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldRaidHpCare(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldRaidHpCare()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldRaidHpCare(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldRaidHpCare
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldRaidHpCare
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidHpCare
    def RaidNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidHpCare
    def StepValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def WorldRaidHpCareStart(builder):
    builder.StartObject(3)

def Start(builder):
    WorldRaidHpCareStart(builder)

def WorldRaidHpCareAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    WorldRaidHpCareAddNo(builder, no)

def WorldRaidHpCareAddRaidNo(builder, raidNo):
    builder.PrependInt32Slot(1, raidNo, 0)

def AddRaidNo(builder, raidNo):
    WorldRaidHpCareAddRaidNo(builder, raidNo)

def WorldRaidHpCareAddStepValue(builder, stepValue):
    builder.PrependInt32Slot(2, stepValue, 0)

def AddStepValue(builder, stepValue):
    WorldRaidHpCareAddStepValue(builder, stepValue)

def WorldRaidHpCareEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldRaidHpCareEnd(builder)
