# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldRaidPartnerBuff(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldRaidPartnerBuff()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldRaidPartnerBuff(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldRaidPartnerBuff
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldRaidPartnerBuff
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidPartnerBuff
    def SubClass(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidPartnerBuff
    def Grade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidPartnerBuff
    def BuffNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidPartnerBuff
    def BuffSno(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorldRaidPartnerBuff
    def BuffIcon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def WorldRaidPartnerBuffStart(builder):
    builder.StartObject(6)

def Start(builder):
    WorldRaidPartnerBuffStart(builder)

def WorldRaidPartnerBuffAddNo(builder, no):
    builder.PrependInt32Slot(0, no, 0)

def AddNo(builder, no):
    WorldRaidPartnerBuffAddNo(builder, no)

def WorldRaidPartnerBuffAddSubClass(builder, subClass):
    builder.PrependInt32Slot(1, subClass, 0)

def AddSubClass(builder, subClass):
    WorldRaidPartnerBuffAddSubClass(builder, subClass)

def WorldRaidPartnerBuffAddGrade(builder, grade):
    builder.PrependInt32Slot(2, grade, 0)

def AddGrade(builder, grade):
    WorldRaidPartnerBuffAddGrade(builder, grade)

def WorldRaidPartnerBuffAddBuffNo(builder, buffNo):
    builder.PrependInt32Slot(3, buffNo, 0)

def AddBuffNo(builder, buffNo):
    WorldRaidPartnerBuffAddBuffNo(builder, buffNo)

def WorldRaidPartnerBuffAddBuffSno(builder, buffSno):
    builder.PrependInt32Slot(4, buffSno, 0)

def AddBuffSno(builder, buffSno):
    WorldRaidPartnerBuffAddBuffSno(builder, buffSno)

def WorldRaidPartnerBuffAddBuffIcon(builder, buffIcon):
    builder.PrependInt32Slot(5, buffIcon, 0)

def AddBuffIcon(builder, buffIcon):
    WorldRaidPartnerBuffAddBuffIcon(builder, buffIcon)

def WorldRaidPartnerBuffEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldRaidPartnerBuffEnd(builder)
