# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Tbl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldRaidBanScoreTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldRaidBanScoreTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldRaidBanScoreTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldRaidBanScoreTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldRaidBanScoreTable
    def Json(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Tbl.WorldRaidBanScore import WorldRaidBanScore
            obj = WorldRaidBanScore()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorldRaidBanScoreTable
    def JsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorldRaidBanScoreTable
    def JsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WorldRaidBanScoreTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    WorldRaidBanScoreTableStart(builder)

def WorldRaidBanScoreTableAddJson(builder, json):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(json), 0)

def AddJson(builder, json):
    WorldRaidBanScoreTableAddJson(builder, json)

def WorldRaidBanScoreTableStartJsonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJsonVector(builder, numElems):
    return WorldRaidBanScoreTableStartJsonVector(builder, numElems)

def WorldRaidBanScoreTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldRaidBanScoreTableEnd(builder)
