namespace DungeonRotationLevel;

table Deserialization {
    no: int32;
    dungeon_no: int32;
    level: int32;
    level_group_no: int32;
    formation_min: int32;
    formation_max: int32;
    monster_type: int32;
    monster_level: int32;
    monster_equip: int32;
    monster_signiture: int32;
    monster_ultimate: int32;
    item_no1: int32;
    amount1: int32;
    item_no2: int32;
    amount2: int32;
    item_no3: int32;
    amount3: int32;
}

table DungeonRotationLevel {
    json: [Deserialization];
}

root_type DungeonRotationLevel;
