namespace EventRaidDrop;

table Deserialization {
    no: int32;
    event_stage_group: int32;
    event_number: int32;
    damage_value: int32;
    drop_item_no1: int32;
    drop_item_amount1: int32;
    drop_item_no2: int32;
    drop_item_amount2: int32;
    drop_item_no3: int32;
    drop_item_amount3: int32;
    drop_item_no4: int32;
    drop_item_amount4: int32;
    drop_item_no5: int32;
    drop_item_amount5: int32;
    is_repeatable: int32;
}

table EventRaidDrop {
    json: [Deserialization];
}

root_type EventRaidDrop;
