# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DungeonInfoUpdate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DungeonInfoUpdate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44ungeonInfoUpdate.proto\x12\x05ReqPb\"\xd2\x02\n\x11\x44ungeonInfoUpdate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01z\x18\x02 \x01(\x02\x12\x11\n\tdungeonId\x18\x03 \x01(\x05\x12\x0f\n\x07mapInfo\x18\x04 \x01(\x0c\x12\x15\n\rconditionInfo\x18\x05 \x01(\x0c\x12\x16\n\x0e\x61\x64\x64itionalInfo\x18\x06 \x01(\x0c\x12\x11\n\trelicInfo\x18\x07 \x01(\x0c\x12\x11\n\tmissionNo\x18\x08 \x01(\x05\x12\x12\n\nmissionCnt\x18\t \x01(\x05\x12\x10\n\x08heroInfo\x18\n \x01(\x0c\x12\x13\n\x0b\x64ungeonItem\x18\x0b \x01(\x0c\x12\x15\n\rultimatePoint\x18\x0c \x01(\x05\x12\x16\n\x0eplayerObjectId\x18\r \x01(\x05\x12\x10\n\x08getRelic\x18\x0e \x03(\x05\x12\x11\n\tloseRelic\x18\x0f \x03(\x05\x12\x1f\n\x17isHiddenKeyNotAvailable\x18\x10 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonInfoUpdate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONINFOUPDATE']._serialized_start=35
  _globals['_DUNGEONINFOUPDATE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
