# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HeroEquipPresetList.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'HeroEquipPresetList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HeroEquipPresetList.proto\x12\x05ReqPb\"n\n\x13HeroEquipPresetList\x12\x12\n\npresetSlot\x18\x01 \x01(\x05\x12\x12\n\npresetName\x18\x02 \x01(\t\x12/\n\npresetHero\x18\x03 \x03(\x0b\x32\x1b.ReqPb.sHeroEquipPresetHero\"Z\n\x14sHeroEquipPresetHero\x12\x0f\n\x07heroIdx\x18\x01 \x01(\t\x12\x31\n\x08itemSlot\x18\x02 \x03(\x0b\x32\x1f.ReqPb.sHeroEquipPresetItemSlot\"=\n\x18sHeroEquipPresetItemSlot\x12\x0c\n\x04slot\x18\x01 \x01(\x05\x12\x13\n\x0bitemEquipId\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroEquipPresetList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEROEQUIPPRESETLIST']._serialized_start=36
  _globals['_HEROEQUIPPRESETLIST']._serialized_end=146
  _globals['_SHEROEQUIPPRESETHERO']._serialized_start=148
  _globals['_SHEROEQUIPPRESETHERO']._serialized_end=238
  _globals['_SHEROEQUIPPRESETITEMSLOT']._serialized_start=240
  _globals['_SHEROEQUIPPRESETITEMSLOT']._serialized_end=301
# @@protoc_insertion_point(module_scope)
