# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OriginTowerExtendStageClear.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'OriginTowerExtendStageClear.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!OriginTowerExtendStageClear.proto\x12\x05ReqPb\"\x7f\n\x1bOriginTowerExtendStageClear\x12\x0f\n\x07towerNo\x18\x01 \x01(\x05\x12\x0f\n\x07stageNo\x18\x02 \x01(\x05\x12\x16\n\x0eremainBattleTs\x18\x03 \x01(\x03\x12\x0f\n\x07heroIdx\x18\x04 \x03(\t\x12\x15\n\ruseRentalHero\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OriginTowerExtendStageClear_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORIGINTOWEREXTENDSTAGECLEAR']._serialized_start=44
  _globals['_ORIGINTOWEREXTENDSTAGECLEAR']._serialized_end=171
# @@protoc_insertion_point(module_scope)
