# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ThreeMatchStageRanking.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'ThreeMatchStageRanking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cThreeMatchStageRanking.proto\x12\x05ReqPb\"\xbe\x01\n\x16ThreeMatchStageRanking\x12)\n\tstageRank\x18\x01 \x03(\x0b\x32\x16.ReqPb.sThreeMatchRank\x12*\n\nfriendRank\x18\x02 \x03(\x0b\x32\x16.ReqPb.sThreeMatchRank\x12\x11\n\tmyPercent\x18\x03 \x01(\x05\x12\x14\n\x0cmyFriendRank\x18\x04 \x01(\x05\x12\x13\n\x0bmyStageRank\x18\x05 \x01(\x05\x12\x0f\n\x07myScore\x18\x06 \x01(\x05\"w\n\x0fsThreeMatchRank\x12\x0f\n\x07userIdx\x18\x01 \x01(\t\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12$\n\tthumbnail\x18\x03 \x01(\x0b\x32\x11.ReqPb.sThumbnail\x12\x0c\n\x04rank\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x05\"b\n\nsThumbnail\x12\x16\n\x0ethumbnailFrame\x18\x01 \x01(\x05\x12\x16\n\x0ethumbnailImage\x18\x02 \x01(\x05\x12\x11\n\tuseCustom\x18\x03 \x01(\x08\x12\x11\n\tthumbnail\x18\x04 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ThreeMatchStageRanking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREEMATCHSTAGERANKING']._serialized_start=40
  _globals['_THREEMATCHSTAGERANKING']._serialized_end=230
  _globals['_STHREEMATCHRANK']._serialized_start=232
  _globals['_STHREEMATCHRANK']._serialized_end=351
  _globals['_STHUMBNAIL']._serialized_start=353
  _globals['_STHUMBNAIL']._serialized_end=451
# @@protoc_insertion_point(module_scope)
